/**
 * This code was generated by Builder.io
 */
import React from 'react';
import TestimonialCarousel from './TestimonialCarousel';

const testimonials = [
  {
    quote: "I love that my daughter is seeing that I'm following my own dreams. As a mother, that's an incredible gift to offer your child.",
    author: "Erin B.",
    image: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/3f697970e938aa88c5d2e80320f1b7fd7bf07a3a676e9063b1e040bf2543ed28?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
  },
];

const TestimonialCarouselWrapper: React.FC = () => {
  return <TestimonialCarousel testimonials={testimonials} />;
};

export default TestimonialCarouselWrapper;