/**
 * This code was generated by Builder.io
 */
"use client";

import React, { useState } from "react";
import TestimonialSlide from "./TestimonialSlide";

interface Testimonial {
  quote: string;
  author: string;
  image: string;
}

interface TestimonialCarouselProps {
  testimonials: Testimonial[];
}

const TestimonialCarousel: React.FC<TestimonialCarouselProps> = ({
  testimonials,
}) => {
  const [currentIndex, setCurrentIndex] = useState(0);

  const handleNext = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % testimonials.length);
  };

  return (
    <section className="flex flex-col items-center bg-gray-900">
      <div className="flex flex-col justify-center px-14 pt-20 pb-20 w-full max-md:px-5 max-md:max-w-full">
        <div className="flex relative flex-col flex-1 justify-center w-full max-md:max-w-full">
          <div className="flex overflow-hidden z-0 flex-col flex-1 w-full max-md:max-w-full">
            <TestimonialSlide
              quote={testimonials[currentIndex].quote}
              author={testimonials[currentIndex].author}
              image={testimonials[currentIndex].image}
            />
          </div>
        </div>
      </div>
    </section>
  );
};

export default TestimonialCarousel;
