/**
 * This code was generated by Builder.io
 */
import React from "react";
import { X } from 'lucide-react';

export interface NotForYouItemProps {
  imageUrl: string;
  content: string;
}

export const NotForYouItem: React.FC<NotForYouItemProps> = ({
  imageUrl,
  content,
}) => {
  return (
    <div className="flex items-start gap-2.5 mt-5 w-full max-md:max-w-full">
      <X 
        className="w-6 h-6 text-red-500" 
        strokeWidth={3}
      />
      <div className="flex-1 text-base font-light tracking-normal leading-6 min-w-[240px] max-md:max-w-full">
        {content}
      </div>
    </div>
  );
};
