/**
 * This code was generated by Builder.io
 */
import React from "react";

interface ContainerProps {
  children: React.ReactNode;
}

const Container: React.FC<ContainerProps> = ({ children }) => {
  return (
    <div className="flex flex-col justify-center px-14 pb-20 w-full max-md:px-5 max-md:max-w-full">
      {children}
    </div>
  );
};

export default Container;
