/**
 * This code was generated by Builder.io
 */
import React from "react";

const Emphasis: React.FC = () => {
  return (
    <div className="flex flex-col pb-1 mt-4 max-md:max-w-full">
      <p className="text-base text-black font-light max-md:max-w-full">
        Alhamdulillah, you've strived <span className="italic text-black">so</span>{" "}
        <span className="font-bold">
          sincerely to honor Allah in your business, health, and relationships. 
          Yet, deep in your heart, you feel a divine calling to something greater - 
          a level of spiritual abundance and feminine power that you{" "}
          <span className="italic">know</span> Allah has written for you, 
          bi'ithnillah.
        </span>
      </p>
    </div>
  );
};

export default Emphasis;
