/**
 * This code was generated by Builder.io
 */
import React from "react";

const Heading: React.FC = () => {
  return (
    <header className="flex flex-col pt-6 pb-2 w-full text-2xl tracking-wide leading-8 text-center text-neutral-800 max-md:max-w-full">
      <div className="w-full text-center max-md:px-5 max-md:max-w-full">
        <h2 className="font-light max-md:max-w-full font-header">
          Ya Ukhti (my dear sister), take a sacred pause and reflect...
        </h2>
        <h3 className="font-bold text-neutral-800 max-md:max-w-full font-header">
          What is disconnection from your divine feminine essence{" "}
          <span className="italic">truly</span> costing your{" "}
          <span className="italic">ruh</span> (soul)?
        </h3>
      </div>
    </header>
  );
};

export default Heading;
