/**
 * This code was generated by Builder.io
 */
import React from "react";

interface MediaLogoProps {
  src: string;
  alt: string;
}

const MediaLogo: React.FC<MediaLogoProps> = ({ src, alt }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain flex-1 h-20 w-full"
    />
  );
};

export default MediaLogo;
