/**
 * This code was generated by Builder.io
 */
import React from "react";

interface ImageContainerProps {
  src: string;
  alt: string;
}

export const ImageContainer: React.FC<ImageContainerProps> = ({ src, alt }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain w-full max-h-[822px] max-w-96"
    />
  );
};
