/**
 * This code was generated by Builder.io
 */
import React from "react";
import { ListItem, ListItemProps } from "./ListItem";
import { ImageContainer } from "./ImageContainer";

interface HighLevelTestminonialProps {}

const listItems: ListItemProps[] = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/d91c0065133a040ec96a1d0f7dbd2113628af32017994c6a42bef5db9d9c0c6d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Sacred Sister Circles:",
    description: "Join your sisters in live spiritual co-working sessions where we align our goals with divine purpose. Whether you're creating your halal business plan, developing your spiritual practice, or seeking clarity through prayer - we're here to support your journey, bi'ithnillah.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/be7fa9219f0c607fe4e95f9b9ce3949b1846ce6d200048d634a9e1771f6e840d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Spiritual Sisterhood & Connection:",
    description: "Finding authentic sisterhood can be challenging in today's world. Alhamdulillah, our sacred space helps you connect with like-minded Muslimahs who understand your journey and support your growth with love and wisdom.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/c5f03a8dddbaa7f258d289736757f6b53df1f8c6084e385890b8fe4d95b782c0?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Halal Business Guidance:",
    description: "Navigate the modern business world while staying true to your Islamic values. We'll guide you through ethical marketing, halal investments, and spiritually aligned business practices that attract barakah.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/047f707cb2df6e68dd14d85960f9881c7e2a3ce0a5af877a0d691750e51adfdc?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Wisdom Sessions with Spiritual Guides:",
    description: "Access the wisdom of renowned Muslim women leaders, spiritual coaches, and successful Muslimah entrepreneurs. These blessed souls share their journey of combining faith with purpose, offering guidance that's rarely available elsewhere.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/35dc438bb1507a71115b4d561c57a8f4f5afbc3f834aca16f7cc6ad7be179a2b?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "\"Blessed Recommendations\":",
    description: "From halal beauty products to Islamic books, modest fashion to spiritual development tools - I'll share resources that support your journey as a modern Muslimah while honoring your values and feminine essence.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/d91c0065133a040ec96a1d0f7dbd2113628af32017994c6a42bef5db9d9c0c6d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Flexible Learning Journey:",
    description: "Allah has blessed us with different life circumstances. If you miss a live session, all recordings are available for you to access at a time that suits your schedule, ensuring you never miss out on the spiritual wisdom shared.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/be7fa9219f0c607fe4e95f9b9ce3949b1846ce6d200048d634a9e1771f6e840d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "PLUS, Exclusive Access to Our Sacred Inner Circle:",
    description: "SubhanAllah, this is your opportunity to receive direct guidance from me, Ramsha, and our blessed community of spiritually aligned sisters. Together, we'll navigate your journey of spiritual awakening and purpose manifestation.",
  },
];
const listItemsTwo: ListItemProps[] = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/d91c0065133a040ec96a1d0f7dbd2113628af32017994c6a42bef5db9d9c0c6d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "LIVE Somatic Healing Circles:",
    description:
      "Join your sisters in sacred healing sessions where we release trauma through gentle somatic practices. Whether you're processing emotions, regulating your nervous system, or seeking deeper embodiment - we create a safe container for your journey, bi'ithnillah.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/be7fa9219f0c607fe4e95f9b9ce3949b1846ce6d200048d634a9e1771f6e840d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Nervous System Support & Integration:",
    description:
      "Our healing journey can bring up deep emotions. Alhamdulillah, our specialized tools and practices help you process and integrate these experiences while staying connected to your faith and feminine wisdom.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/c5f03a8dddbaa7f258d289736757f6b53df1f8c6084e385890b8fe4d95b782c0?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Body-Based Spiritual Practices:",
    description:
      "Discover how to embody your prayers, regulate your nervous system during worship, and create deeper physical connection with your spiritual practices. We'll explore halal ways to honor both your body and your deen.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/047f707cb2df6e68dd14d85960f9881c7e2a3ce0a5af877a0d691750e51adfdc?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Sacred Sessions with Somatic Healers:",
    description:
      "Access the wisdom of experienced Muslim somatic practitioners and spiritual guides who understand both Islamic principles and nervous system healing. These blessed teachers share practices that honor both faith and embodiment.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/35dc438bb1507a71115b4d561c57a8f4f5afbc3f834aca16f7cc6ad7be179a2b?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "\"Healing Resources & Recommendations\":",
    description:
      "From prayer beads to healing tools, movement practices to spiritual books - I'll share resources that support your embodiment journey while honoring Islamic principles and feminine wisdom.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/d91c0065133a040ec96a1d0f7dbd2113628af32017994c6a42bef5db9d9c0c6d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "Flexible Healing Journey:",
    description:
      "Allah knows our unique circumstances. All healing sessions are recorded for you to access at your own pace, ensuring you can integrate the practices in a way that honors your nervous system's capacity.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/be7fa9219f0c607fe4e95f9b9ce3949b1846ce6d200048d634a9e1771f6e840d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    title: "PLUS, Exclusive Access to Our Healing Circle:",
    description:
      "SubhanAllah, receive direct somatic guidance from me, Ramsha, and our community of embodied sisters. Together, we'll navigate the sacred path of healing while staying anchored in our faith.",
  },
];

const HighLevelTestminonial: React.FC<HighLevelTestminonialProps> = () => {
  return (
    <section className="flex flex-col px-14 pt-20 pb-20 max-md:px-5">
      <header className="flex flex-col self-center pt-4 pb-6 max-w-full text-4xl text-center leading-[54px] text-neutral-800 w-[775px]">
        <h2 className="px-28 w-full italic max-md:px-5 max-md:max-w-full">
          <span className="text-neutral-800">
            What Awaits You in The Awakened Feminine?
          </span>
          <br />
          <span className="italic text-neutral-800">Bismillah, Let's Explore...</span>
        </h2>
      </header>
      <div className="space-y-8">
        <div className="grid md:grid-cols-[.75fr_1fr] gap-10 max-w-5xl.5 mx-auto">
          <div className="flex items-center justify-center">
            <ImageContainer
              src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/c77e04de91102339e35ea3c945cc61b447b2207f2ed34594fdae038be332c6c5?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
              alt="Dream Club visual representation"
            />
          </div>
          <div className=" max-md:max-w-full">
            <ul className="flex flex-col gap-5 w-full max-md:max-w-full">
              {listItemsTwo.map((item, index) => (
                <ListItem key={index} {...item} />
              ))}
            </ul>
          </div>
        </div>
        <div className="md:grid md:grid-cols-[1fr_.75fr] flex flex-col-reverse items-center gap-10 max-w-5xl.5 mx-auto">
          <div className="">
            <ul className="flex flex-col gap-5 w-full max-md:max-w-full">
              {listItems.map((item, index) => (
                <ListItem key={index} {...item} />
              ))}
            </ul>
          </div>
          <ImageContainer
            src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/ff6a39f700e6f03b192a9e7d862e7d27aa383890b748dc1c4704d5004ae300a2?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
            alt="Additional Dream Club visual"
          />
        </div>
      </div>
    </section>
  );
};

export default HighLevelTestminonial;
