/**
 * This code was generated by Builder.io
 */
import React from "react";
import Image from "next/image";

export interface ListItemProps {
  icon: string;
  title: string;
  description: string;
}

export const ListItem: React.FC<ListItemProps> = ({
  icon,
  title,
  description,
}) => {
  return (
    <li className="flex flex-wrap items-start mt-5 w-full max-md:max-w-full">
      <div className="flex flex-col items-start pt-px pr-2 w-7 max-w-[514px]">
        <Image
          src={icon}
          alt=""
          className="object-contain aspect-square w-[21px]"
          width={21}
          height={21}
        />
      </div>
      <div className="flex-1 pr-2 text-base tracking-normal leading-6 text-black min-w-[240px] max-md:max-w-full">
        <strong className="text-black">{title}</strong>{" "}
        <span className="font-light text-black">{description}</span>
      </div>
    </li>
  );
};
