/**
 * This code was generated by Builder.io
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <img
      src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/089736cacc36049a138f7d8e96b0cd3ead577ba42ff957c74d5243a0f7780294?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
      alt="Company Logo"
      className="object-contain self-stretch w-full aspect-[11.24] max-md:max-w-full"
    />
  );
};

export default Logo;
