/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroContent from "./HeroContent";
import HeroImage from "./HeroImage";
import BlurFade from "@/components/magicui/blur-fade";

const HeroSection: React.FC = () => {
  return (
    <section className="flex flex-col md:flex-row max-lg:px-8 max-md:px-5">
      <div className="w-full md:w-1/2 pb-10">
        <BlurFade inViewMargin="-200px">
          <HeroContent />
        </BlurFade>
      </div>
      <div className="w-full md:w-1/2">
        <BlurFade inViewMargin="-200px">
          <HeroImage />
        </BlurFade>
      </div>
    </section>
  );
};

export default HeroSection;
