/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroImage: React.FC = () => {
  return (
    // <div className="lg:-mt-28 relative z-10">
    //   <div className="flex flex-col grow justify-center items-start ">
    //     <img
    //       
    //       src="/hero-2.svg"
    //       alt="Marie's portrait"
    //       className="relative z-10 max-lg:w-full h-full max-w-xl bottom-0"
    //     />
    //   </div>
    // </div>
    <img
      
      src="/hero-2.svg"
      alt="Ramsha's portrait"
      className="w-full h-full"
    />
  );
};

export default HeroImage;
