/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroSection from "./HeroSection";

const LandingPage: React.FC = () => {
  return (
    <main className="flex justify-center relative bg-stone-200">
      <div className="w-full md:pl-[60px]">
        <HeroSection />
      </div>
    </main>
  );
};

export default LandingPage;
