/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

const imageData = [
  "/spotify.png",
  "/apple.png",
  "/pandora.png",
  "/pocket.png",
  "/castbox.png",
];

const PodcastListenOn: React.FC = () => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
      {imageData.map((item) => (
        <Image
          src={item}
          height={50}
          width={200}
          alt="podcasts"
          key={item}
          className="object-contain w-full max-h-16 md:max-h-12"
        />
      ))}
    </div>
  );
};

export default PodcastListenOn;
