/**
 * This code was generated by Builder.io
 */
import React from "react";
import FAQItem from "./FAQItem";

interface FAQData {
  question: string;
  id: string;
}

const faqData: FAQData[] = [
  {
    question:
      "What if my schedule doesn't line up with your live sessions, will I miss out?",
    id: "schedule",
  },
  { question: "How much is Dream Club?", id: "price" },
  {
    question: "How much time will I need to invest in Dream Club?",
    id: "time-investment",
  },
  {
    question: "How long will I have access to Dream Club?",
    id: "access-duration",
  },
  { question: "What happens after December 1st, 2024?", id: "post-december" },
  { question: "What's your refund policy?", id: "refund-policy" },
  {
    question: "I don't have a business yet — can I still join Dream Club?",
    id: "no-business",
  },
  {
    question:
      "I'm a professional within a team — not a business owner. Can I still join Dream Club?",
    id: "professional",
  },
  {
    question: "I have another question not answered here. How can I ask it?",
    id: "other-questions",
  },
];

const FAQSection: React.FC = () => {
  return (
    <section className="flex flex-col items-center bg-stone-50">
      <div className="flex flex-col px-14 pt-20 pb-24 w-full max-md:px-5 max-md:max-w-full">
        <h2 className=" pt-4 pb-6 max-w-full text-4xl text-center leading-[54px] text-neutral-800">
          <span className="w-full max-md:px-5 max-md:max-w-full">
            Questions? Ask Away!
          </span>
        </h2>
        <div className="flex flex-col items-center w-full min-h-[320px] max-md:max-w-full">
          <div className="flex flex-col gap-2.5 w-full bg-stone-50 max-w-[1000px] max-md:max-w-full">
            {faqData.map((item) => (
              <FAQItem key={item.id} question={item.question} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;
