/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FormInputProps {
  label: string;
  type: string;
  id: string;
  placeholder: string;
}

const FormInput: React.FC<FormInputProps> = ({
  label,
  type,
  id,
  placeholder,
}) => {
  return (
    <div className="flex flex-1 shrink items-start pb-1.5 h-full basis-0 w-full ">
      <div className="flex overflow-hidden flex-col pt-3 pr-px pb-5 pl-4 bg-white border border-black border-solid min-h-[50px]   w-full">
        <label htmlFor={id} className="sr-only">
          {label}
        </label>
        <input
          type={type}
          id={id}
          placeholder={placeholder}
          className="overflow-hidden w-full"
          aria-label={label}
        />
      </div>
    </div>
  );
};

export default FormInput;
