/**
 * This code was generated by Builder.io
 */
import React from "react";
interface TestimonialCardProps {
  imageSrc: string;
  quote: string;
  author: string;
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  imageSrc,
  quote,
  author,
}) => {
  return (
    <div className="md:grid md:grid-cols-[110px_1fr] flex flex-col justify-center p-5 max-md:max-w-full">
      <div className="flex md:justify-end justify-center  relative md:left-5 max-md:top-3.5">
        <img
          loading="lazy"
          src={imageSrc}
          alt={`${author}'s profile`}
          className="object-contain w-[110px] max-md:mr-0"
        />
      </div>
      <div className="flex relative z-10 flex-col py-5 pr-7 pl-9 rounded-2xl border border-black border-solid bg-gray-50 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col w-full tracking-normal leading-6 text-black   max-md:max-w-full">
          <p className="text-base font-light">{quote}</p>
        </div>
        <div className="flex flex-col self-start pt-4 text-sm font-bold tracking-widest leading-6 text-center uppercase text-red-600">
          <p>{author}</p>
        </div>
      </div>
    </div>
  );
};

export default TestimonialCard;
