/**
 * This code was generated by Builder.io.
 */
import BlurFade from "@/components/magicui/blur-fade";
import React from "react";
import Image from "next/image";

type ContentSectionProps = {
  title: any;
  subtitle: string;
  description: string;
  buttonText: string;
  buttonLink?: string;
  imageSrc: string;
  imageAlt: string;
  reverse?: boolean;
  textContainerClassName?: string;
  imageContainerClassName?: string;
  backgroundColor?: string;
};

const ContentSection: React.FC<ContentSectionProps> = ({
  title,
  subtitle,
  description,
  buttonText,
  buttonLink,
  imageSrc,
  imageAlt,
  textContainerClassName = "col-span-6",
  imageContainerClassName = "col-span-6",
  backgroundColor,
}) => {
  return (
    <section 
      className="flex flex-col items-center w-full py-11 px-5 lg:py-24 lg:px-7"
      style={{ backgroundColor: backgroundColor }}
    >
      <div className="flex flex-col w-full max-w-5xl.5">
        <BlurFade>
          <div className="flex flex-col md:flex-row w-full md:items-center md:gap-8">
            <div
              className={`flex flex-col ${textContainerClassName} text-neutral-800 md:w-1/2 w-full order-2 md:order-1`}
            >
              <div className="z-10 pb-px text-xs font-[700] leading-5 uppercase tracking-[2.16px]">
                {subtitle}
              </div>
              <h2 className="mt-6 text-[32px] md:text-[42px] lg:text-[40px] leading-[1.3] md:leading-[1.2] font-caslon font-[700]">
                {title}
              </h2>
              <p className="pb-px mt-5 text-lg tracking-normal leading-[1.6] md:leading-8 text-black font-[600]">
                {description}
              </p>
              <a
                href={buttonLink}
                className="overflow-hidden z-10 px-6 md:px-16 py-4 md:py-4 mt-6 text-base font-bold tracking-wide leading-6 text-center text-white capitalize rounded-full bg-ramsha-tertiary w-full md:w-fit shadow-button hover:shadow-button-hover font-[700]"
              >
                {buttonText}
              </a>
            </div>
            <div className={`${imageContainerClassName} md:w-1/2 w-full flex justify-center md:justify-end items-start order-1 md:order-2 mb-8 md:mb-0`}>
              <Image
                src={imageSrc}
                alt={imageAlt}
                className="object-contain w-full max-w-[335px] md:max-w-none md:w-full"
                width={335}
                height={140}
              />
            </div>
          </div>
        </BlurFade>
      </div>
    </section>
  );
};

export default ContentSection;
