/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PodcastSectionItem from "./PodcastSectionItem";

const PodcastSection: React.FC = () => {
  return (
    <PodcastSectionItem
      title="The Marie Forleo Podcast"
      description="Named by Oprah as a thought leader for the next generation and owner of one of Inc.'s 500 fastest growing companies, Marie Forleo's goal is to help you become the person you most want to be. Marie and her guests share actionable strategies for greater happiness, success, motivation, creativity, productivity, love, health, contribution, and fulfillment — often with a lot of laughs."
    />
  );
};

export default PodcastSection;
