/**
 * This code was generated by Builder.io.
 */
'use client'
import React from "react";
import { motion } from "framer-motion";

interface PodcastInfoProps {
  title: string;
  description: any;
}

const PodcastInfo: React.FC<PodcastInfoProps> = ({ title, description }) => {
  return (
    <>
      <motion.h2 
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ 
          duration: 0.6,
          ease: "easeOut",
          delay: 0.4 // Delay after card animation
        }}
        viewport={{ once: true }}
        className="text-4xl tracking-wider leading-[62.4px] text-neutral-800 max-md:px-5 max-md:max-w-full font-caslon font-[700]"
      >
        {title}
      </motion.h2>
      
      <motion.p 
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ 
          duration: 0.6,
          ease: "easeOut",
          delay: 0.5 // Slightly after title
        }}
        viewport={{ once: true }}
        className="mt-7 text-base tracking-normal leading-8 text-black max-md:max-w-full"
      >
        {description}
      </motion.p>
    </>
  );
};

export default PodcastInfo;
