/**
 * This code was generated by Builder.io
 */
import React from "react";
import ListItem from "./ListItem";
import { ListItemProps } from "./ListItem";
import Image from "next/image";

interface DreamClubListProps {
  imageSrc: string;
}

const listItems: ListItemProps[] = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "Financial freedom, personal freedom, and the kind of joy that turns heads",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "A streamlined path to business growth (no burnout here!)",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "A strong and healthy body, a loving heart, and a sharp, creative mind",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "Support to stay on track with your most important goals, in business and life",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "A profoundly positive place to connect, share, learn, and grow",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "Your #DreamTeam of professionals who've got your back",
  },
];

const DreamClubList: React.FC<DreamClubListProps> = ({ imageSrc }) => {
  return (
    <section className="grid grid-cols-[.75fr_1fr] max-md:grid-cols-1 justify-center">
      <img
        loading="lazy"
        src={imageSrc}
        alt="Dream Club visual representation"
        className="object-cover object-right  h-full w-full max-md:max-h-[300px] xl:max-h-[788px]  max-md:max-w-full"
      />
      <div className="flex bg-stone-50 py-24 max-md:max-w-full">
        <div className="flex flex-col justify-center gap-4 max-w-full px-10 max-md:px-5">
          <div className="flex flex-col gap-2 text-base font-light tracking-normal leading-7 text-black max-md:max-w-full">
            <h4 className=" w-full text-2xl font-light tracking-wide leading-8 text-neutral-800 max-md:max-w-full">
              Dream Club is a profoundly positive place where you can
              <span className="font-bold text-neutral-800">
                {" "}
                achieve your BIG goals{" "}
              </span>
              in business and life, <span className="italic">without</span>{" "}
              sacrificing your joy or health.
            </h4>
            <p className=" w-full max-md:max-w-full">
              You&apos;re invited to join me, Team Forleo, and my inner circle
              of colleagues, friends, and experts as we all build forward from
              where we are today, to where we want to be. Together, we&apos;ll
              hit new levels of wealth, joy, and freedom.
            </p>
            <p className=" w-full max-md:max-w-full">
              Dream Club provides the mindsets, strategies, and support you need
              to create…
            </p>
          </div>
          <div className="flex flex-col max-md:max-w-full">
            <ul className="flex flex-col w-full max-md:max-w-full">
              {listItems.map((item, index) => (
                <ListItem
                  key={index}
                  imageSrc={item.imageSrc}
                  text={item.text}
                />
              ))}
            </ul>
          </div>
          <div className="flex flex-col pb-4 text-base font-light tracking-normal leading-7 text-black max-md:max-w-full">
            <p className="w-full max-md:max-w-full">
              So you can enjoy a rich and adventure-filled life{" "}
              <span className="italic">now</span> — not &quot;someday.&quot;
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DreamClubList;
