/**
 * This code was generated by Builder.io
 */
import React from "react";

export interface ListItemProps {
  imageSrc: string;
  text: string;
}

const ListItem: React.FC<ListItemProps> = ({ imageSrc, text }) => {
  return (
    <li className="flex items-start mt-4 w-full max-md:max-w-full">
      <div className="flex flex-col items-start pt-2 pr-4 max-w-[491px] w-[61px]">
        <img
          
          src={imageSrc}
          alt=""
          className="object-contain aspect-[4.61] w-[46px]"
        />
      </div>
      <p className="pr-px text-base font-light tracking-normal leading-6 text-black min-w-[240px]">
        {text}
      </p>
    </li>
  );
};

export default ListItem;
