/**
 * This code was generated by Builder.io
 */
import React from "react";

export const TextContainer: React.FC = () => {
  const paragraphs = [
    {
      text: "Nurturing your mind, body, and soul in alignment with Islamic principles is essential for manifesting your divine purpose and living an extraordinary life blessed by Allah.",
      isItalic: false,
    },
    {
      text: "Because let's be real, sister: balancing dunya responsibilities while staying connected to your spiritual essence isn't always easy.",
      isBold: true,
    },
    "If you don't surround yourself with spiritually aligned sisters who uplift you — especially during times of trial — it becomes difficult to manifest your highest potential that Allah has written for you.",
    "The Awakened Feminine is not like any other spiritual program.",
    "This is a sacred space of divine abundance, spiritual growth, and soul-led transformation.",
    "No judgment.\nNo ego.\nNo negativity.\nJust pure, sacred sisterhood.",
    {
      text: "Alhamdulillah, we're authentically devoted to joyful spiritual growth, feminine energy activation, and divinely guided success - in both dunya and akhirah.",
      isUnderlined: true,
    },
  ];

  return (
    <div className="flex flex-col pb-4 w-full tracking-normal max-md:max-w-full">
      {paragraphs.map((paragraph, index) => (
        <p
          key={index}
          className={`mt-4 w-full max-md:max-w-full ${
            typeof paragraph === "object"
              ? paragraph.isItalic
                ? "italic"
                : paragraph.isBold
                  ? "font-bold"
                  : paragraph.isUnderlined
                    ? "underline decoration-auto decoration-solid underline-offset-auto"
                    : ""
              : ""
          }`}
        >
          {typeof paragraph === "string" ? paragraph : paragraph.text}
        </p>
      ))}
    </div>
  );
};
