/**
 * This code was generated by Builder.io
 */
import React from 'react';
import TestimonialCarousel from './TestimonialCarousel';

const testimonials = [
  {
    quote: "‟Alhamdulillah, working with Ramsha transformed not just my business but my entire relationship with success. She taught me how to build wealth while honoring my deen, and how to embody my feminine power without compromising my values. The somatic healing work helped me release years of stored tension and finally trust in Allah's timing.",
    author: "Amira K., Business Owner",
    image: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/a2873e36d397b0bbf45ace820a1d839a4317bbf1c2a104dc03ac5a2e03313aac?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
  },
  {
    quote: "‟The nervous system work was revolutionary for me as a Muslimah entrepreneur. I learned how to navigate success while staying deeply connected to my spiritual essence. Ramsha's guidance helped me understand that my feminine energy is a gift from Allah, not something to suppress.",
    author: "Fatima R., Creative Director",
    image: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/a2873e36d397b0bbf45ace820a1d839a4317bbf1c2a104dc03ac5a2e03313aac?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
  },
  {
    quote: "‟SubhanAllah, this program was exactly what I needed. It's not just about business growth - it's about healing the relationship between your spiritual self and worldly success. The sisterhood and support have been incredible, and I've finally found peace in pursuing my ambitions while staying true to my faith.",
    author: "Noor S., Coach & Mentor",
    image: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/a2873e36d397b0bbf45ace820a1d839a4317bbf1c2a104dc03ac5a2e03313aac?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
  }
];

const TestimonialCarouselWrapper: React.FC = () => {
  return <TestimonialCarousel testimonials={testimonials} />;
};

export default TestimonialCarouselWrapper;