/**
 * This code was generated by Builder.io
 */
import * as React from "react";
import { TextBlock } from "./TextBlock";
import { Button } from "./Button";

export const DreamClub: React.FC = () => {
  return (
    <main className="w-full min-h-screen bg-gradient-to-b from-black via-black to-neutral-900 text-white text-center px-4 md:px-16">
      <section className="max-w-[900px] mx-auto py-12">
        <header className="mb-8">
          <TextBlock 
            text="Ramsha Suhail Invites You" 
            className="text-xs uppercase tracking-[2.16px] text-ramsha-tertiary"
          />
        </header>

        <h1 className="font-serif text-4xl md:text-7xl leading-tight md:leading-[100px] mb-8">
          Join the VIP Waitlist <br /> for Awakened Feminine!
        </h1>

        <section className="text-lg font-light leading-8 mb-8">
          <p className="mb-4">
            <TextBlock text="Dream Club isn't just another business program. It's a" />
            <TextBlock text="lifestyle revolution" isBold={true} />
            <TextBlock text="for ambitious, wildly magical creators committed to doing business and life differently…" />
          </p>

          <TextBlock
            text="SPACES ARE LIMITED & THEY FILL UP FAST."
            className="mb-4"
          />

          <TextBlock
            text="Join the VIP Waitlist now to get first dibs..."
            className="italic"
          />
        </section>

        <div className="max-w-[388px] mx-auto mb-8">
          <Button 
            text="GET ON THE VIP WAITLIST NOW" 
            className="w-full bg-[#E5B5A7] text-black rounded-full px-8 py-4 font-medium tracking-wider" 
          />
        </div>

        <footer className="text-sm">
          <div className="flex justify-center items-center gap-1">
            <TextBlock text="Don't see the sign-up button?" />
            <TextBlock text="Click here" className="text-[#E5B5A7]" />
            <TextBlock text="to join." />
          </div>
        </footer>
      </section>
    </main>
  );
};
