/**
 * This code was generated by Builder.io
 */
import React from "react";
import Heading from "./Heading";
import JoinWaitlist from "./JoinWaitlist";
import BlurFade from "@/components/magicui/blur-fade";

interface ContentItem {
  text: string;
  alignment: "left" | "right" | "center";
}

const contentItems: ContentItem[] = [
  { text: "Continuous\nevolution", alignment: "left" },
  { text: "profoundly\npositive", alignment: "right" },
  { text: "formless\ninto form", alignment: "left" },
];

const ContinuousEvolution: React.FC = () => {
  return (
    <section className="flex flex-col items-center bg-black">
      <div className="flex flex-col px-10 pt-14 pb-5 w-full max-md:px-5 max-md:max-w-full">
        {contentItems.map((item, index) => (
          <BlurFade key={index}>
            <Heading
              text={item.text}
              alignment={item.alignment}
              className={index > 0 ? "mt-96 max-md:mt-10" : ""}
            />
          </BlurFade>
        ))}
        <BlurFade>
          <div className="flex flex-wrap gap-5 justify-center mt-32 max-md:mt-10 max-md:max-w-full">
            <div className="flex flex-col grow shrink pt-3 pb-4 text-2xl font-light tracking-wide leading-8 text-orange-50 min-w-[240px] w-[246px]">
              <h4 className="pr-1 w-full">
                <span className="text-orange-50">
                  Helping you build a richer,
                </span>
                <br />
                <span className="font-bold text-orange-50">
                  more satisfying life
                </span>
                <span className="text-orange-50">.</span>
              </h4>
            </div>
            <div className="flex flex-col grow shrink justify-center items-end pt-11 pb-12 w-full max-w-[388px]">
              <div className="flex max-w-full bg-white min-h-[1px] w-[388px]" />
            </div>
            <JoinWaitlist />
          </div>
        </BlurFade>
      </div>
    </section>
  );
};

export default ContinuousEvolution;
