/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

interface ImageComponentProps {
  src: string;
  alt: string;
  className: string;
}

const ImageComponent: React.FC<ImageComponentProps> = ({
  src,
  alt,
  className,
}) => {
  return (
    <Image
      src={src}
      alt={alt}
      className={className}
      width={500}
      height={300}
    />
  );
};

export default ImageComponent;
