/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PodcastSectionItem from "./PodcastSectionItem";

const PodcastSection: React.FC = () => {
  return (
    <PodcastSectionItem
      title="RICH RECEIVER"
      description={
        <span className="text-center text-xl leading-relaxed">
          <span className="mb-8">
            When you embody your feminine energy,<br/>
            you will receive gifts from Allah like a Queen of Paradise.
          </span>
          <br/>
          <span>
            Get instant access to my best-selling meditation that will relax<br/>
            your body into a deep, loving state of surrender - so you can<br/>
            relax & let God Give you His Gifts ↓
          </span>
        </span>
      }
    />
  );
};

export default PodcastSection;
