/**
 * This code was generated by Builder.io
 */
import React from "react";
import { TextBlock } from "./TextBlock";
import { Heading } from "./Heading";
import BlurFade from "@/components/magicui/blur-fade";

interface BookSectionProps {
  imageSrc: string;
}

const BookSection: React.FC<BookSectionProps> = ({ imageSrc }) => {
  const textBlocks = [
    {
      content:
        "Alhamdulillah, I've been blessed to study with spiritual teachers and healers across the globe 🌙. But the true secret to my spiritual abundance and sustainable success as a Muslim woman is that I never walk this path alone.",
      isItalic: true,
    },
    {
      content:
        "I surround myself with spiritually aligned sisters. Women who uplift and inspire me. I collaborate with those who understand both deen and dunya. I remain in the beautiful position of a student, always learning, always growing. These sacred connections are the foundation of my heart, my purpose, and every blessing Allah allows me to share with the ummah.",
      isItalic: false,
    },
    {
      content:
        "As Muslims, we know this truth deeply. The Prophet ﷺ taught us that we are on the deen of our close companions. The energy and intention you surround yourself with shapes your thoughts, your heart, and ultimately — who Allah guides you to become.",
      isItalic: false,
    },
    {
      content:
        "If you've read this far, ya ukhti (my dear sister), I believe Allah has guided you to your spiritual family.",
      isItalic: true,
      isBold: true,
    },
    {
      content: "We see your light. We're here to help you shine, bi'ithnillah.",
      isItalic: false,
    },
    {
      content:
        "Because the ummah truly needs that unique divine gift that Allah has blessed only you with.",
      isItalic: true,
    },
  ];

  return (
    <section className="grid md:grid-cols-[1fr_1.25fr] justify-center bg-ramsha-primary">
      <img
        loading="lazy"
        src={imageSrc}
        alt="Ramsha with students"
        className="object-cover w-full h-full xl:max-h-[825px] max-md:max-w-full"
      />
      <div className="flex flex-col grow shrink justify-center items-start py-20 max-md:px-5 max-md:max-w-full">
        <BlurFade>
          <div className="flex flex-col p-10 relative md:right-24 rounded-2xl border border-black border-solid bg-stone-50 max-md:px-5 max-md:max-w-full">
            <Heading />
            {textBlocks.map((block, index) => (
              <TextBlock key={index} {...block} />
            ))}
          </div>
        </BlurFade>
      </div>
    </section>
  );
};

export default BookSection;
