/**
 * This code was generated by Builder.io
 */
import React from "react";

export const Heading: React.FC = () => {
  return (
    <header className="flex flex-col pt-4 pb-2 w-full text-2xl font-bold tracking-wide leading-8 text-neutral-800 max-md:max-w-full">
      <h2 className="flex flex-col w-full max-md:max-w-full">
        <strong className="max-md:max-w-full">
          If Books, Courses, and Podcasts <br /> Were Enough, You'd Have The
          Results
        </strong>
        <strong className="underline decoration-auto decoration-solid underline-offset-auto">
          <span className="text-neutral-800">You Deserve</span>
          <span className="text-neutral-800"> By Now.</span>
        </strong>
      </h2>
    </header>
  );
};
