/**
 * This code was generated by Builder.io
 */
import React from "react";

export const Heading: React.FC = () => {
  return (
    <header className="flex flex-col pt-4 pb-2 w-full text-2xl font-bold tracking-wide leading-8 text-neutral-800 max-md:max-w-full">
      <h2 className="flex flex-col w-full max-md:max-w-full">
        <strong className="max-md:max-w-full">
          If Knowledge Alone Was Enough, <br /> Your Soul Would Already Feel The
          Connection
        </strong>
        <strong className="underline decoration-auto decoration-solid underline-offset-auto">
          <span className="text-neutral-800">Allah Created You For</span>
          <span className="text-neutral-800">, Bi'ithnillah.</span>
        </strong>
      </h2>
      <p className="text-base font-light mt-2 italic">
        True transformation requires embodiment of both spiritual wisdom and feminine power
      </p>
    </header>
  );
};
