/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TextBlockProps {
  content: string;
  isItalic?: boolean;
  isBold?: boolean;
}

export const TextBlock: React.FC<TextBlockProps> = ({
  content,
  isItalic = false,
  isBold = false,
}) => {
  const baseClasses = "mt-4 w-full max-md:max-w-full";
  const italicClasses = isItalic ? "italic" : "";
  const boldClasses = isBold ? "font-bold" : "font-light";

  return (
    <p
      className={`${baseClasses} ${italicClasses} ${boldClasses} text-base tracking-normal leading-7 text-black`}
    >
      {content}
    </p>
  );
};
