/**
 * This code was generated by Builder.io
 */
import React from "react";
import { TextBlock } from "./TextBlock";
import { ImageBlock } from "./ImageBlock";

interface PlugIntoCommunitySectionProps {}

const PlugIntoCommunitySection: React.FC<PlugIntoCommunitySectionProps> = () => {
  return (
    <section className="flex flex-wrap justify-center">
      <TextBlock />
      <ImageBlock />
    </section>
  );
};

export default PlugIntoCommunitySection;
