/**
 * This code was generated by Builder.io
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex flex-col w-full max-md:max-w-full">
      <h1 className="flex flex-col mx-auto items-center py-1.5 w-full md:text-[50px] text-[32px] font-bold text-center md:leading-[65px] leading-[40px] lg:w-[420px]">
        Get Instant Clarity & Achieve Your Goals with Less Stress
      </h1>
      <h2 className="py-1.5 mt-1.5 w-full md:text-[26px] text-[20px] font-bold leading-8 text-center text-orange-600 max-md:max-w-full">
        With Your Free "Yearly Goals Map"
      </h2>
      <p className="pt-2.5 pr-2 pb-1.5 pl-2 mt-1.5 w-full md:text-[18px] text-[17px] font-[400] leading-7 text-center max-md:max-w-full">
        This simple, powerful, fast, and FREE tool will help you clarify
        your most important goals — and let go of what's holding you back
        — in 10 minutes or less.
      </p>
      <p className="flex flex-col items-center px-1 pt-1.5 mt-1.5 w-full md:text-[20px] text-[18px] font-bold leading-7 text-center max-md:max-w-full">
        Enter your name and email below and I'll
        send your FREE Yearly Goals Map straight
        to your inbox…
      </p>
    </header>
  );
};

export default Header;
