/**
 * This code was generated by Builder.io
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex flex-col px-5 w-full max-md:max-w-full">
      <h1 className="flex flex-col items-center px-2 py-1.5 w-full text-5xl font-bold text-center leading-[65px] max-md:max-w-full">
        <span className="max-md:text-4xl">Get Instant</span>
        <span className="max-md:text-4xl max-md:leading-[58px]">
          Clarity & Achieve <br /> Your Goals with <br /> Less Stress
        </span>
      </h1>
      <h2 className="px-9 py-1.5 mt-1.5 w-full text-2xl font-bold leading-8 text-center text-orange-600 max-md:px-5 max-md:max-w-full">
        With Your Free "Yearly Goals <br /> Map"
      </h2>
      <p className="pt-2.5 pr-2 pb-1.5 pl-2 mt-1.5 w-full text-lg font-thin leading-7 text-center max-md:max-w-full">
        This simple, powerful, fast, and FREE tool will <br /> help you clarify
        your most important goals — and <br /> let go of what's holding you back
        — in 10 minutes <br /> or less.
      </p>
      <p className="flex flex-col items-center px-1 pt-1.5 mt-1.5 w-full text-xl font-bold leading-7 text-center max-md:max-w-full">
        <span>Enter your name and email below and I'll</span>
        <span>send your FREE Yearly Goals Map straight</span>
        <span>to your inbox…</span>
      </p>
    </header>
  );
};

export default Header;
