/**
 * This code was generated by Builder.io
 */
import React from "react";

const ImageSection: React.FC = () => {
  return (
    <section className="flex flex-col flex-1 shrink px-4 pt-12 basis-0 min-h-[1px] min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col px-5 w-full max-md:max-w-full">
        <div className="flex flex-col justify-center items-center w-full max-md:max-w-full">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/b5545ceb3d9f83a4ef51ee112bc2a2bc991ec217627f181328bc6f360cdebf09?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
            alt="Yearly Goals Map preview"
            className="object-contain w-full aspect-[0.77] max-w-[422px] max-md:max-w-full"
          />
        </div>
        <div className="flex flex-col justify-center items-center px-40 pt-1 pb-0.5 mt-8 w-full max-md:px-5 max-md:max-w-full">
          <div className="flex overflow-hidden items-start w-full max-w-[422px]">
            <div className="flex overflow-hidden flex-col justify-center items-center min-h-[14px] w-[100px]">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/81252b7afdeaa2a320972e6b841157d5c14f9143e0f7551526d1ca1810b63478?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
                alt="Marie Forleo Logo"
                className="object-contain w-full aspect-[7.09]"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default ImageSection;
