/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import Form from "./Form";
import ImageSection from "./ImageSection";

const YearlyGoalsMap: React.FC = () => {
  return (
    <main className="flex flex-col items-center px-2.5 pt-14 pb-16 bg-white border-red-200 border-solid border-[10px]">
      <div className="flex flex-wrap items-start px-2.5 pb-8 max-w-full w-[1004px]">
        <section className="flex flex-col flex-1 shrink px-4 pt-4 text-black basis-0 min-h-[1px] min-w-[240px] max-md:max-w-full">
          <Header />
          <Form />
        </section>
        <ImageSection />
      </div>
    </main>
  );
};

export default YearlyGoalsMap;
