/**
 * This code was generated by Builder.io
 */
import React from "react";

export const Heading: React.FC = () => {
  return (
    <header className="flex flex-col pt-2 pb-3.5 w-full text-4xl leading-[54px] text-neutral-800 max-md:max-w-full">
      <h1 className="w-full italic max-md:max-w-full">
        <span className="text-neutral-800">The Dream Club</span>
        <br />
        <span className="italic text-neutral-800">Difference</span>
      </h1>
    </header>
  );
};
