/**
 * This code was generated by Builder.io
 */
import React from "react";

export const Heading: React.FC = () => {
  return (
    <header className="flex flex-col pt-2 pb-3.5 w-full text-4xl leading-[54px] text-neutral-800 max-md:max-w-full">
      <h1 className="w-full text-neutral-800 max-md:max-w-full">
        The Sacred <span className="italic">Sisterhood</span>{" "}
        <span className="font-light">Experience</span>
      </h1>
    </header>
  );
};
