/**
 * This code was generated by Builder.io
 */
import React from "react";

export const TextContainer: React.FC = () => {
  const paragraphs = [
    {
      text: "Taking care of yourself mentally, emotionally, and physically is critical to building a successful business and living an extraordinary life.",
      isItalic: true,
    },
    {
      text: "Because let's be real: running a business (and managing life) isn't all rainbows and unicorns.",
      isBold: true,
    },
    "If you don't surround yourself with positive, ambitious people — especially when the shiitake hits the fan —it's impossible to realize your fullest potential.",
    "Dream Club is not like any other program.",
    "This is a place of prosperity, possibility and forward movement.",
    "No politics.\nNo pitching.\nNo rants.",
    {
      text: "In other words, we're unapologetically optimistic, joyful, and realistically ambitious about whole-life growth and success.",
      isUnderlined: true,
    },
  ];

  return (
    <div className="flex flex-col pb-4 w-full tracking-normal max-md:max-w-full">
      {paragraphs.map((paragraph, index) => (
        <p
          key={index}
          className={`mt-4 w-full max-md:max-w-full ${
            typeof paragraph === "object"
              ? paragraph.isItalic
                ? "italic"
                : paragraph.isBold
                ? "font-bold"
                : paragraph.isUnderlined
                ? "underline decoration-auto decoration-solid underline-offset-auto"
                : ""
              : ""
          }`}
        >
          {typeof paragraph === "string" ? paragraph : paragraph.text}
        </p>
      ))}
    </div>
  );
};
