/**
 * This code was generated by Builder.io
 */
import React from "react";
import Image from "next/image";

export interface QuestionItemProps {
  imageUrl: string;
  question: string;
}

export const QuestionItem: React.FC<QuestionItemProps> = ({
  imageUrl,
  question,
}) => {
  return (
    <div className="flex flex-wrap items-start mt-5 w-full max-md:max-w-full">
      <div className="flex flex-col items-start pt-1 pr-2.5 max-w-[758px] w-[31px]">
        <Image
          src={imageUrl}
          alt=""
          className="object-contain aspect-[1.17] w-[21px]"
          width={21}
          height={18}
        />
      </div>
      <div className="text-base font-light tracking-normal leading-6 text-black min-w-[240px]">
        {question}
      </div>
    </div>
  );
};
