/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SupportSection: React.FC = () => {
  return (
    <section className="flex flex-col items-start pt-2 pb-2.5 mt-11 w-full max-md:mt-10">
      <div className="flex items-center max-w-full w-[124px]">
        <div className="flex overflow-hidden items-start self-stretch my-auto">
          <div className="flex overflow-hidden flex-col justify-center items-center min-h-[31px] w-[27px]">
            <img
              
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/aff7fbcea89077a1a5c3ed193547eeacc01fd5eae12e539591ad59eda8a78bd3?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a"
              alt=""
              className="object-contain w-full aspect-[0.87]"
            />
          </div>
        </div>
        <p className="self-stretch pl-3.5 my-auto text-sm italic tracking-wider leading-7 text-white">
          Need Help?
        </p>
      </div>
    </section>
  );
};

export default SupportSection;
