/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StudentSuccessStories from "./StudentSuccessStory";

interface Story {
  category: string;
  testimonial: string;
  author: string;
}

const stories: Story[] = [
  {
    category: "B-School",
    testimonial:
      "The EXACT messages I needed to hear to kick me in the bum, get me started and, most importantly, to BELIEVE in myself.",
    author: "Bonnie U.",
  },
];

const StudentSuccessStoriesWrapper: React.FC = () => {
  return <StudentSuccessStories stories={stories} />;
};

export default StudentSuccessStoriesWrapper;
