/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import NewsletterSignup from "./NewsletterSignup";
import CompanyLinks from "./CompanyLinks";
import CoursesLinks from "./CoursesLinks";
import SupportSection from "./SupportSection";
import ProgramLogin from "./ProgramLogin";
import LegalLinks from "./LegalLinks";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col items-center px-32 bg-black max-md:px-5">
      <div className="flex flex-col px-8 py-28 w-full max-w-[1200px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
        <Logo />
        <div className="flex flex-wrap items-start">
          <NewsletterSignup />
          <CompanyLinks />
          <CoursesLinks />
        </div>
        <SupportSection />
        <ProgramLogin />
        <LegalLinks />
      </div>
    </footer>
  );
};

export default Footer;
