/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NewsletterSignup: React.FC = () => {
  return (
    <section className="flex flex-col grow shrink py-5 pr-9 text-white min-h-[1px] min-w-[240px] w-[418px] max-md:max-w-full">
      <h2 className="pb-px text-xs font-extrabold leading-5 uppercase tracking-[2.16px] max-md:max-w-full">
        Become an MF Insider
      </h2>
      <p className="mt-3 text-sm tracking-normal leading-6 max-md:max-w-full">
        Sign up for exclusive content, emails & things Marie doesn't share
        <br />
        anywhere else.
      </p>
    </section>
  );
};

export default NewsletterSignup;
