/**
 * This code was generated by Builder.io.
 */
import React from "react";
// import { ImageItem } from "./ImageItem";
import Image from "next/image";
import BlurFade from "@/components/magicui/blur-fade";

const imageData = [
  [
    { src: "/gridImages/image41.png" },
    { src: "/gridImages/image6.png" },
    { src: "/gridImages/image7.png" },
  ],
  [
    { src: "/gridImages/image8.png" },
    { src: "/gridImages/image23.png" },
  ],
  [
    { src: "/gridImages/image24.png" },
    { src: "/gridImages/image25.png" },
    { src: "/gridImages/image6.png" },
  ],
  [
    { src: "/gridImages/image28.png" },
    { src: "/gridImages/image31.png" },
    { src: "/gridImages/image10.png" },
  ],
  [
    { src: "/gridImages/image32.png" },
    { src: "/gridImages/image36.png" },
  ],
];

export default function ImageGallery() {
  return (
    <section className="w-full px-4 max-w-[2000px] mx-auto">
      {imageData.map((item, idx) => (
        <div
          key={idx + "root"}
          className="flex max-md:flex-col gap-5 mb-5"
        >
          {item.map((image, index) => (
            <BlurFade key={index} inViewMargin="-200px">
              <div className="relative md:flex-1">
                <Image
                  src={image.src}
                  width={500}
                  height={400}
                  className="w-full md:h-[300px] lg:h-[400px] xl:h-[500px] object-cover rounded-sm transition-transform hover:scale-[1.02] duration-300"
                  alt="Gallery image"
                />
              </div>
            </BlurFade>
          ))}
        </div>
      ))}
    </section>
  );
}
