/**
 * This code was generated by Builder.io
 */
import React from "react";
import { DreamsWorthSection } from "./DreamsWorthSection";

const dreamItems = [
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "SubhanAllah, your divine inspirations are manifesting with ease. The alignment between your body, soul, and purpose creates a beautiful flow of barakah!",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "When challenges arise — whether in business, health, or relationships — you're surrounded by a sisterhood that understands both spiritual and practical wisdom.",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "Your relationship with Allah feels more connected than ever. Your nervous system is regulated, your heart is at peace, and you're experiencing joy in ways you never imagined possible, Alhamdulillah!",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "When you see your reflection, you recognize the nur (divine light) radiating from within. Your body feels like a trusted friend, not something to fight against.",
    isItalic: true,
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "Setting boundaries feels natural and aligned. Your energy is protected for what truly matters - your relationship with Allah, your purpose, and your loved ones.",
    isItalic: true,
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "Your schedule honors both deen and dunya. You've created sacred time for ibadah, self-care, rest, and inspired action in your business.",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "You're planning meaningful gatherings with your soul sisters - because deep spiritual connection combined with joyful sisterhood nourishes both heart and spirit.",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "Your body feels like a sanctuary - you're sleeping deeply, eating nourishing foods, moving with joy, and feeling more embodied in your feminine energy than ever before.",
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "Your home has become a haven of peace and beauty, reflecting the harmony you feel within. Every corner supports your spiritual and emotional wellbeing.",
    isItalic: true,
  },
  {
    iconSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/25a324412ab9c5d4104fa76a1247afada975d8aed2035eb0747c100d6cdafeff?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    content:
      "Those whispers of inspiration Allah placed in your heart... they're blossoming into reality through divine timing and alignment!",
  },
];

const SomaticHealing: React.FC = () => {
  return (
    <DreamsWorthSection
      title="What Is Your Spiritual Transformation Worth?"
      subtitle="Bi'ithnillah, envision yourself when..."
      imageSrc="/ramsha-pics/webp/gf77.webp"
      dreamItems={dreamItems}
      conclusion={[
        "How would this level of embodied spiritual alignment transform your life?",
        "Your investment in this sacred container is an investment in your relationship with Allah, yourself, and your divine purpose.",
      ]}
    />
  );
};

export default SomaticHealing;
