/**
 * This code was generated by Builder.io
 */
import React from "react";
import { TextBlock } from "./TextBlock";
import { ImageBlock } from "./ImageBlock";

interface PlugIntoCommunitySectionProps {}

const PlugIntoCommunitySection: React.FC<
  PlugIntoCommunitySectionProps
> = () => {
  return (
    <section className="grid md:grid-cols-[1fr_.75fr] ">
      <TextBlock />
      <ImageBlock />
    </section>
  );
};

export default PlugIntoCommunitySection;
