/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TextBlockProps {}

export const TextBlock: React.FC<TextBlockProps> = () => {
  const paragraphs = [
    {
      text: "As a Muslimah, your spiritual and worldly success is deeply influenced by the sisters you surround yourself with, for the Prophet ﷺ taught us that we are on the deen of our close companions.",
      isItalic: false,
    },
    {
      text: "Alhamdulillah, you may have wonderful people in your life. But if they hold limiting beliefs about abundance, success, or feminine power - or if they approach life from a place of fear or scarcity mindset - it can impact your own spiritual and professional growth.",
      isItalic: true,
    },
    {
      text: "Allah ﷻ has given you the beautiful power of choice - to decide who you want to become and how you want to manifest your divine purpose.",
      isBold: true,
    },
    {
      text: "Choose with tawakkul (trust in Allah).",
      isItalic: false,
    },
    {
      text: "SubhanAllah, you carry within you so many divine gifts and unique contributions to share with the ummah. Your journey of spiritual awakening and feminine embodiment is just beginning. Together, bi'ithnillah, we'll transform those whispers of inspiration into divine manifestation.",
      isItalic: true,
    },
  ];

  return (
    <div className="flex flex-col grow shrink items-center bg-stone-50 leading-[54px] min-w-[240px] text-neutral-800 max-md:max-w-full">
      <div className="flex flex-col px-12 py-20 max-w-full max-md:px-5">
        <h2 className="font-caslon flex flex-col pt-2.5 pb-3.5 text-4xl max-md:max-w-full">
          Join our Sacred Sisterhood. <br /> Awaken your Divine Feminine. <br /> 
          Manifest with Purpose.
        </h2>
        <h3 className="font-montserrat-bold pt-2.5 pb-3.5 text-3xl max-md:max-w-full">
          Experience <span className="italic">spiritual abundance</span> along the way.
        </h3>
        <div className="flex flex-col pt-5 text-base font-light tracking-normal leading-7 text-black max-md:max-w-full">
          {paragraphs.map((paragraph, index) => (
            <p
              key={index}
              className={`mt-4 w-full max-md:max-w-full ${
                paragraph.isItalic ? "italic" : ""
              } ${paragraph.isBold ? "font-bold" : ""}`}
            >
              {paragraph.text}
            </p>
          ))}
        </div>
      </div>
    </div>
  );
};
