/**
 * This code was generated by Builder.io
 */
import * as React from "react";

interface FooterLinkProps {
  href: string;
  children: React.ReactNode;
  className?: string;
}

export const FooterLink: React.FC<FooterLinkProps> = ({ href, children, className }) => {
  return (
    <a 
      href={href} 
      className={`text-white no-underline ${className}`}
    >
      {children}
    </a>
  );
};
