/**
 * This code was generated by Builder.io
 */
import * as React from "react";
import { FooterLink } from "./FooterLinks";

const links = [
  { href: "#", text: "TERMS" },
  { href: "#", text: "PRIVACY" },
  { href: "#", text: "SUPPORT" },
];

export const Footer: React.FC = () => {
  return (
    <footer className="flex justify-between items-center px-8 py-4 bg-black text-white w-full">
      {/* Logo */}
      <div className="flex items-center">
        <h2 className="text-lg font-bold tracking-wider uppercase">
          Awakened Feminine
        </h2>
      </div>

      {/* Navigation */}
      <nav className="flex gap-6">
        {links.map((link, index) => (
          <FooterLink 
            key={index} 
            href={link.href}
            className="text-xs tracking-wider hover:text-gray-300 transition-colors"
          >
            {link.text}
          </FooterLink>
        ))}
      </nav>
    </footer>
  );
};
