/**
 * This code was generated by Builder.io
 */
import React from "react";
import ListItem from "./ListItem";
import { ListItemProps } from "./ListItem";
import Image from "next/image";

interface DreamClubListProps {
  imageSrc: string;
}

const listItems: ListItemProps[] = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "Authentic abundance (rizq) and spiritual freedom that radiates from within, attracting barakah in all areas of your life",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "A divinely guided path to growth that honors your feminine energy (no masculine hustle culture!)",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "A balanced mind, body, and soul alignment through Islamic principles and somatic healing practices",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "Spiritual sisterhood supporting you in manifesting your divine purpose, both in dunya and akhirah",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "A sacred space for deep connection, spiritual growth, and authentic transformation",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/de254eda4b272aa4a643d1eaf25f19a0703b0c515d9173c471809f621c1c999e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    text: "Your soul sisters and spiritual mentors who understand your journey",
  },
];

const DreamClubList: React.FC<DreamClubListProps> = ({ imageSrc }) => {
  return (
    <section className="grid grid-cols-[.75fr_1fr] max-md:grid-cols-1 justify-center">
      <img
        loading="lazy"
        src={imageSrc}
        alt="Awakened Feminine visual representation"
        className="object-cover object-right h-full w-full max-md:max-h-[300px] xl:max-h-[788px] max-md:max-w-full"
      />
      <div className="flex bg-stone-50 py-24 max-md:max-w-full">
        <div className="flex flex-col justify-center gap-4 max-w-full px-10 max-md:px-5">
          <div className="flex flex-col gap-2 text-base font-light tracking-normal leading-7 text-black max-md:max-w-full">
            <h4 className="font-header w-full text-2xl font-light tracking-wide leading-8 text-neutral-800 max-md:max-w-full">
              Bismillah. The Awakened Feminine is a sacred space where you can
              <span className="font-bold text-neutral-800">
                {" "}
                manifest your divine purpose{" "}
              </span>
              and elevate your soul, <span className="italic">while</span>{" "}
              honoring your feminine essence.
            </h4>
            <p className="w-full max-md:max-w-full">
              You're invited to join me, your spiritual sisters, and our circle of 
              healers and mentors as we journey together from where Allah has placed 
              us today, to where He has destined us to be. Together, we'll reach new 
              levels of spiritual abundance, inner peace, and authentic freedom.
            </p>
            <p className="w-full max-md:max-w-full">
              The Awakened Feminine provides the spiritual wisdom, healing practices, 
              and divine support you need to create…
            </p>
          </div>
          <div className="flex flex-col max-md:max-w-full">
            <ul className="flex flex-col w-full max-md:max-w-full">
              {listItems.map((item, index) => (
                <ListItem
                  key={index}
                  imageSrc={item.imageSrc}
                  text={item.text}
                />
              ))}
            </ul>
          </div>
          <div className="flex flex-col pb-4 text-base font-light tracking-normal leading-7 text-black max-md:max-w-full">
            <p className="w-full max-md:max-w-full">
              So you can embody your highest self and divine purpose{" "}
              <span className="italic">now</span> — bi'ithnillah (by Allah's permission).
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DreamClubList;
