/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FreeTrainingButtonProps {
  className?: string;
}

const FreeTrainingButton: React.FC<FreeTrainingButtonProps> = ({ className = '' }) => {
  return (
    <button className={`font-subheader w-full md:w-[250px] whitespace-nowrap lg:px-4 xl:px-8 pt-2.5 pb-3 text-sm lg:text-base text-center text-white capitalize bg-ramsha-tertiary rounded-md shadow-button cursor-pointer hover:shadow-button-hover max-md:px-5 ${className}`}>
      <a
        href="/free-hypnosis-lead"
        target="_blank"
        rel="noopener noreferrer"
      >
        Free Training
      </a>
    </button>
  );
};

export default FreeTrainingButton;
