/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import FreeTrainingButton from "./FreeTrainingButton";
import { AlignJustify } from "lucide-react";

const Header: React.FC = () => {
  return (
    <header className="flex flex-col pb-px bg-white border-b border-solid border-b-zinc-400 w-full max-lg:py-5">
      <div className="flex gap-10 justify-between items-center px-7 w-full max-md:px-5 max-md:max-w-full">
        <Logo />
        <div className="flex items-center max-lg:hidden">
          <Navigation />
          <FreeTrainingButton />
        </div>
        <div className="lg:hidden ">
          <AlignJustify />
        </div>
      </div>
    </header>
  );
};

export default Header;
