/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { LearnHeader } from "./LearnHeader";
import { LearnImage } from "./LearnImage";

const LearnAnything: React.FC = () => {
  return (
    <div className="bg-ramsha-accent md:px-2 lg:px-0">
      <section className="flex flex-col md:flex-row py-20 max-md:px-5">
        <div className="w-full lg:w-3/5 flex justify-center items-center">
          <LearnHeader />
        </div>
        <div className="w-full md:w-[300px] lg:w-2/5 flex justify-center items-center">
          <LearnImage />
        </div>
      </section>
    </div>
  );
};

export default LearnAnything;
