/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { LearnHeader } from "./LearnHeader";
import { LearnImage } from "./LearnImage";
import BlurFade from "@/components/magicui/blur-fade";

const LearnAnything: React.FC = () => {
  return (
    <main className="flex flex-col bg-stone-50">
      <BlurFade>
        <section className="flex flex-col py-20 w-full max-md:px-5 md:py-20 max-md:max-w-full max-w-[1000px] mx-auto">
          <div className="flex flex-col md:flex-row">
            <div className="w-full md:w-1/2">
              <LearnHeader />
            </div>
            <div className="w-full md:w-1/2 flex justify-end mx-auto items-center">
              <LearnImage />
            </div>
          </div>
        </section>
      </BlurFade>
    </main>
  );
};

export default LearnAnything;
