/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SubscriptionForm from "./Form/SubscriptionForm";
export const LearnHeader: React.FC = () => {
  return (
    <header className="flex flex-col grow gap-5 shrink px-2.5 pt-2.5 pb-8 tracking-normal leading-9 text-center text-black min-h-[1px] max-md:max-w-full">
      <h1 className="text-xl lg::text-3xl font-ivy-presto tracking-wider leading-[48.6px] text-neutral-800 max-md:px-5 max-md:max-w-full ">
        <span className="text-neutral-800">Learn How to Get </span>
        <span className="italic text-neutral-800">Anything</span>
        <span className="text-neutral-800"> You Want</span>
      </h1>
      <div>
        <p className=" lg:text-lg max-md:mr-1.5">
          <span className="text-black">
            Listen to this FREE audio from Marie and learn the{" "}
          </span>
          <span className="font-bold text-black">3 steps that&apos;ll </span>
          <span className="font-bold">change</span>{" "}
          <span className="text-black font-bold">your life, </span>
          <span className="italic text-black font-bold">fast.</span>
        </p>
      </div>
      <SubscriptionForm />
    </header>
  );
};
