'use client'
/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import SubscriptionForm from "./Form/SubscriptionForm";

export const LearnHeader: React.FC = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
        delayChildren: 0.3
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.6,
        ease: "easeOut"
      }
    }
  };

  return (
    <motion.header
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="flex flex-col grow gap-5 shrink px-4 lg:px-8 pt-2.5 pb-8 tracking-normal leading-9 text-center text-black md:w-[380px] lg:w-[570px] xl:w-full"
    >
      <motion.h1 
        variants={itemVariants}
        className="text-xl lg:text-[32px] font-caslon tracking-wider md:leading-[24px] lg:leading-[48.6px] text-neutral-800 max-md:px-5 mx-auto"
      >
        <motion.span 
          variants={itemVariants}
          className="text-neutral-800 font-[600]"
        >
          Learn How to Get Your Prayers Answered{" "}
        </motion.span>
        <motion.span 
          variants={itemVariants}
          className="italic text-neutral-800"
        >
          Instantly
        </motion.span>
      </motion.h1>

      <motion.div variants={itemVariants}>
        <p className="lg:text-lg max-md:mr-1.5">
          <motion.span 
            variants={itemVariants}
            className="text-black leading-[24px] lg:leading-[48.6px] block"
          >
            Listen to this FREE hypnosis from Ramsha and learn the
          </motion.span>
          <motion.span 
            variants={itemVariants}
            className="font-bold text-black block"
          >
            ONE key shift that will put you on speed dial with God,
          </motion.span>
          <motion.span 
            variants={itemVariants}
            className="italic text-black font-bold block"
          >
            by relaxing your body.
          </motion.span>
        </p>
      </motion.div>

      <motion.div
        variants={itemVariants}
        className="w-full"
      >
        <SubscriptionForm />
      </motion.div>
    </motion.header>
  );
};
