/**
 * This code was generated by Builder.io.
 */
'use client'

import React from "react";
import Image from "next/image";
import { motion } from "framer-motion";

export const LearnImage: React.FC = () => {
  const imageVariants = {
    hidden: { 
      opacity: 0, 
      y: 40,
      scale: 0.95
    },
    visible: { 
      opacity: 1, 
      y: 0,
      scale: 1,
      transition: {
        duration: 0.8,
        ease: "easeOut",
        delay: 0.2
      }
    }
  };

  return (
    <motion.div
      variants={imageVariants}
      initial="hidden"
      animate="visible"
      className="w-full md:w-[500px] lg:w-[300px]"
    >
      <Image
        src="/cta-image-2.webp"
        className="object-contain w-full"
        alt="Learn Anything illustration"
        width={500}
        height={250}
        priority
      />
    </motion.div>
  );
};
