/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

export const LearnImage: React.FC = () => {
  return (
    <Image
      src="/cta-image-2.webp"
      className="object-contain w-full md:w-[500px] lg:w-[300px]"
      alt="Learn Anything illustration"
      width={500}
      height={250}
    />
  );
};
