/**
 * This code was generated by Builder.io
 */
import React from "react";
import ImageComponent from "./ImageComponent";

const MainComponent: React.FC = () => {
  return (
    <main>
      <section>
        <ImageComponent
          src="/ramsha-pics-v2/gf6.jpeg"
          alt="Main content image"
        />
      </section>
    </main>
  );
};

export default MainComponent;
