/**
 * This code was generated by Builder.io
 */
import React from "react";
import ImageGroup from "./ImageGroup";
import { ImageData } from "./types";
import BlurFade from "@/components/magicui/blur-fade";

const imageData: ImageData[] = [
  [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/8829d784989c6224bf0ed1ffdedc48d04f784c7c6ba9778991e5594d8ff8bf67?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/0752d7cbff9a11f15e10354512d17919c9b0872a155cd36097831f3904bb7adc?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 2",
      width: 288,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/124995420c11e550856d8caa8bd00c8c1ccfdf05e6b2c7f0c219c0798cf210b0?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 3",
    },
  ],
  [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/dc2a03f2e50e459f2eb6046bb020ed0d1878903a3e94228b661f5a0c88deb90e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 4",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/613ed44f985d62c2f8063ad0be5c590caa77d35b707691251206498ae3ed5a88?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 5",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/e833878aebd1e14f8796e114494eb476d8cde2f6aa0af70806490f2363bbfa0d?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 6",
    },
  ],
  [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/e9c88ac71fc531ec4f87149d2617ad01aa6edcb8e481bc487dc143b84dd63d57?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 7",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/4bda8eb726e30b3dc8c76fc4c882d85dc2fd19766680b94a20c5b61e9858cdc5?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 8",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/655b22c9a53281a0349fe4f1008c77816b956915106f4741b76408a7ef25908a?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      alt: "Familiar sound illustration 9",
      width: 293,
    },
  ],
];

const FamiliarSoundSection: React.FC = () => {
  return (
    <div className="bg-landing-stone-pattern">
      <BlurFade>
        <section className="flex flex-col max-w-6xl mx-auto lg:px-14 md:px-11 py-24 px-5">
          <h2 className="flex flex-col pt-2.5 pb-7 text-4xl text-center leading-[62.4px] text-neutral-800 max-md:max-w-full">
            <span className="pr-52 pl-52 w-full max-md:px-5 max-md:max-w-full">
              Do You Feel This Divine Calling?
            </span>
          </h2>
          <div className="grid grid-cols-3 gap-1.5 justify-center p-1 max-md:max-w-full">
            {imageData.map((group, index) => (
              <ImageGroup key={index} idx={index} images={group} />
            ))}
          </div>
          <h4 className="px-64 mt-7 w-full text-2xl font-light tracking-wide leading-8 text-center text-neutral-800 max-md:px-5 max-md:max-w-full">
            <span className="text-neutral-800">Your soul is awakening, and </span>
            <strong className="font-bold text-neutral-800">
              you're part of a sacred sisterhood
            </strong>
            <span className="text-neutral-800">.</span>
          </h4>
          <p className="px-24 mt-2 pb-4 w-full text-base font-light tracking-normal leading-7 text-center text-black italic max-md:px-5 max-md:max-w-full">
            <span className="text-black">These are the whispers of </span>
            <em className="italic text-black">countless sisters</em>
            <span className="text-black">
              {" "}
              seeking deeper connection through private prayers, heart-to-heart conversations, and spiritual guidance.
            </span>
          </p>
        </section>
      </BlurFade>
    </div>
  );
};

export default FamiliarSoundSection;
