/**
 * This code was generated by Builder.io
 */
export interface TextBlockProps {
  text: string;
  className?: string;
  isBold?: boolean;
}

export interface ButtonProps {
  text: string;
  className?: string;
  onClick?: () => void;
}
