/**
 * This code was generated by Builder.io
 */
'use client'

import React from "react";
import { motion } from "framer-motion";

const Header: React.FC = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
        delayChildren: 0.3
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.6,
        ease: "easeOut"
      }
    }
  };

  return (
    <motion.header
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="flex flex-col w-full max-md:max-w-full"
    >
      <motion.h1 
        variants={itemVariants}
        className="flex flex-col font-header mx-auto items-center py-1.5 w-full md:text-[50px] text-[32px] font-bold text-center md:leading-[65px] leading-[40px] lg:w-[420px]"
      >
        Learn How to Get Your Prayers Answered <i>Instantly</i>
      </motion.h1>
      
      <motion.div variants={itemVariants}>
        <p className="pt-2.5 pr-2 pb-1.5 pl-2 mt-1.5 w-full md:text-[18px] text-[17px] font-[400] leading-7 text-center max-md:max-w-full">
          Listen to this FREE training from Ramsha and learn the ONE key shift that will put you on speed dial with God, <i>by relaxing your body.</i>
        </p>
      </motion.div>

      <motion.p 
        variants={itemVariants}
        className="flex font-header flex-col items-center px-1 pt-1.5 mt-1.5 w-full md:text-[20px] text-[18px] font-bold leading-7 text-center max-md:max-w-full"
      >
        Enter your name and email below...
      </motion.p>
    </motion.header>
  );
};

export default Header;
