/**
 * This code was generated by Builder.io
 */
'use client'

import React from "react";
import { motion } from "framer-motion";
import { Sparkles, Heart, Award, Users } from 'lucide-react';
import Image from 'next/image';

const Header: React.FC = () => {
  return (
    <motion.header className="flex flex-col w-full">
      {/* Hero Section (with image26.webp) */}
      <div className="relative py-20">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            {/* Text Content */}
            <motion.div 
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
              viewport={{ once: true }}
              className="flex flex-col text-left"
            >
              <span className="text-xs uppercase tracking-[2px] text-ramsha-tertiary mb-4">
                Awakened Feminine Mastermind
              </span>
              <h1 className="text-3xl md:text-5xl lg:text-6xl font-header leading-tight mb-6 text-ramsha-primary">
                Somatic Healing & <span className="italic">Nervous System</span> Expansion
              </h1>
              <p className="text-lg md:text-xl text-ramsha-primary/80 max-w-xl mb-8">
                For high-achieving Muslim women awakening their feminine power & embodying unshakable trust in Allah.
              </p>
              <p className="text-lg md:text-xl text-ramsha-primary/90 italic mb-12">
                "In the deepest states of relaxation, you access your inner wisdom. Like an Awakened Queen"
              </p>
            </motion.div>

            {/* Image */}
            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.7, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="relative aspect-[3/4] rounded-2xl overflow-hidden">
                <Image
                  src="/gridImages/webp/image26.webp"
                  alt="Awakened Feminine"
                  fill
                  className="object-cover object-center hover:scale-105 transition-transform duration-700"
                  priority
                  quality={100}
                />
                {/* Decorative elements */}
                <div className="absolute inset-0 bg-gradient-to-t from-ramsha-primary/10 to-transparent" />
                <div className="absolute -inset-0.5 bg-ramsha-tertiary/10 backdrop-blur-[2px] opacity-30" />
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      {/* New Status Quo Section */}
      <div className="relative w-full overflow-hidden my-20">
        <div className="max-w-7xl mx-auto">
          <div className="relative aspect-[16/9] md:aspect-[21/9]">
            <Image
              src="/gridImages/webp/image32.webp" // Make sure to add this image to your public folder
              alt="Modern interior with wooden stairs"
              fill
              className="object-cover"
              quality={100}
            />
            
            {/* Text Overlay */}
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
              viewport={{ once: true }}
              className="absolute inset-0 flex items-center justify-start p-8 md:p-16"
            >
              <h2 className="text-3xl md:text-5xl lg:text-6xl font-header text-white max-w-2xl leading-tight">
                You Do Not Have To
                <br />
                Settle for the{" "}
                <span className="italic">Status Quo.</span>
              </h2>
            </motion.div>

            {/* Gradient Overlay */}
            <div className="absolute inset-0 bg-gradient-to-r from-black/40 to-transparent" />
          </div>
        </div>
      </div>

      {/* Features Grid */}
      <div className="max-w-6xl mx-auto px-4 py-16">
        <div className="grid md:grid-cols-2 gap-8">
          {[
            {
              icon: <Sparkles className="w-12 h-12 text-ramsha-tertiary mb-4" />,
              title: "Weekly Nervous System Expansion",
              description: "Experience targeted healing sessions that combine Quranic wisdom with somatic practices."
            },
            {
              icon: <Heart className="w-12 h-12 text-ramsha-tertiary mb-4" />,
              title: "Rich Receiver Method™",
              description: "Release trauma permanently while deepening your connection with Allah."
            },
            {
              icon: <Award className="w-12 h-12 text-ramsha-tertiary mb-4" />,
              title: "Become a Certified Healer",
              description: "Transform your healing journey into expertise with our Year 2 program."
            },
            {
              icon: <Users className="w-12 h-12 text-ramsha-tertiary mb-4" />,
              title: "2-Day NYC Retreat",
              description: "Join our signature graduation retreat for deep connection and celebration."
            }
          ].map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 + (index * 0.1) }}
              viewport={{ once: true }}
              className="bg-white rounded-2xl p-8 shadow-xl hover:shadow-2xl transition-all duration-300"
            >
              {feature.icon}
              <h3 className="text-xl font-semibold mb-4">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Call to Action */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.6 }}
        viewport={{ once: true }}
        className="text-center max-w-3xl mx-auto px-4 pb-16"
      >
        <h2 className="text-2xl md:text-3xl font-semibold mb-4 text-ramsha-primary">
          Begin Your Healing Journey
        </h2>
        <p className="text-lg text-ramsha-primary/80 mb-4">
          Join our transformative 12-month mastermind and access the wisdom of your body, heart, and soul.
        </p>
        <p className="text-sm text-gray-600 italic">
          Limited spots available for this intimate container
        </p>
      </motion.div>
    </motion.header>
  );
};

export default Header;
