/**
 * This code was generated by Builder.io.
 */
import React from "react";
import RichReceiver from "./RichReceiver";

const Component: React.FC = () => {
  return (
    <section className="bg-ramsha-primary">
      <RichReceiver />
    </section>
  );
};

export default Component;
