/**
 * This code was generated by Builder.io
 */
import React from "react";
import { DreamListItem, DreamListItemProps } from "./DreamListItem";

interface DreamsWorthSectionProps {
  title: string;
  subtitle: string;
  imageSrc: string;
  dreamItems: DreamListItemProps[];
  conclusion: string[];
}

export const DreamsWorthSection: React.FC<DreamsWorthSectionProps> = ({
  title,
  subtitle,
  imageSrc,
  dreamItems,
  conclusion,
}) => {
  return (
    <section className="grid md:grid-cols-[.75fr_1fr] bg-black">
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className="object-cover w-full h-full max-md:max-w-full max-md:max-h-[400px] lg:max-h-[1480px] xl:max-h-[1160px]"
      />
      <div className="max-md:max-w-full">
        <div className="h-full px-12 py-20 max-w-full max-md:px-5">
          <header className="flex flex-col pt-2.5 pb-4 max-md:max-w-full">
            <h2 className="w-full text-4xl text-orange-50 leading-[54px] max-md:max-w-full">
              {title}
            </h2>
            <p className="mt-3.5 w-full text-base font-bold tracking-normal leading-7 text-orange-100 max-md:max-w-full">
              {subtitle}
            </p>
          </header>
          <ul className="flex flex-col pb-2.5 max-md:max-w-full">
            {dreamItems.map((item, index) => (
              <DreamListItem key={index} {...item} />
            ))}
          </ul>
          <footer className="flex flex-col pt-5 text-base font-light tracking-normal leading-7 text-orange-100 max-md:max-w-full">
            {conclusion.map((paragraph, index) => (
              <p key={index} className="mt-4 w-full max-md:max-w-full">
                {paragraph}
              </p>
            ))}
          </footer>
        </div>
      </div>
    </section>
  );
};
