/**
 * This code was generated by Builder.io
 */
import React from "react";
import { DreamListItem, DreamListItemProps } from "./DreamListItem";
import Image from "next/image";

interface DreamsWorthSectionProps {
  title: string;
  subtitle: string;
  imageSrc: string;
  dreamItems: DreamListItemProps[];
  conclusion: string[];
}

export const DreamsWorthSection: React.FC<DreamsWorthSectionProps> = ({
  title,
  subtitle,
  imageSrc,
  dreamItems,
  conclusion,
}) => {
  return (
    <section className="flex flex-wrap justify-center bg-black">
      <Image
        src={imageSrc}
        alt=""
        className="object-contain grow shrink aspect-[0.3] min-w-[240px] w-[351px] max-md:max-w-full"
        width={351}
        height={117}
      />
      <div className="flex flex-col grow shrink items-center min-w-[240px] w-[497px] max-md:max-w-full">
        <div className="flex flex-col px-12 py-20 max-w-full w-[585px] max-md:px-5">
          <header className="flex flex-col pt-2.5 pb-4 max-md:max-w-full">
            <h2 className="w-full text-4xl text-orange-50 leading-[54px] max-md:max-w-full">
              {title}
            </h2>
            <p className="mt-3.5 w-full text-base font-bold tracking-normal leading-7 text-orange-100 max-md:max-w-full">
              {subtitle}
            </p>
          </header>
          <ul className="flex flex-col pb-2.5 max-md:max-w-full">
            {dreamItems.map((item, index) => (
              <DreamListItem key={index} {...item} />
            ))}
          </ul>
          <footer className="flex flex-col pt-5 text-base font-light tracking-normal leading-7 text-orange-100 max-md:max-w-full">
            {conclusion.map((paragraph, index) => (
              <p key={index} className="mt-4 w-full max-md:max-w-full">
                {paragraph}
              </p>
            ))}
          </footer>
        </div>
      </div>
    </section>
  );
};
