/**
 * This code was generated by Builder.io
 */
import React from "react";

export interface DreamListItemProps {
  iconSrc: string;
  content: string;
  isItalic?: boolean;
}

export const DreamListItem: React.FC<DreamListItemProps> = ({
  iconSrc,
  content,
  isItalic = false,
}) => {
  return (
    <li className="flex items-start mt-4 w-full max-md:max-w-full">
      <div className="flex flex-col items-start pt-1.5 pr-2.5 max-w-[486px] w-[30px]">
        <img
          
          src={iconSrc}
          alt=""
          className="object-contain w-5 aspect-[1.25]"
        />
      </div>
      <p
        className={`pr-6 text-base font-light tracking-normal leading-6 text-orange-50 min-w-[240px] max-md:max-w-full ${
          isItalic ? "italic" : ""
        }`}
      >
        {content}
      </p>
    </li>
  );
};
