/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroParralax: React.FC = () => {
  return (
    <div 
      className="
        bg-[url('/gridImages/webp/image30.webp')] 
        bg-cover 
        bg-no-repeat 
        w-full 
        min-h-[300px]
        md:min-h-[600px]
        lg:min-h-[600px]
        md:bg-fixed
        lg:bg-[50%_30%]
      " 
    />
  );
};

export default HeroParralax;
