/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroParralax: React.FC = () => {
  return (
    <div className="bg-fixed bg-[url(https://cdn.prod.website-files.com/5f2ae813361eff3ad9282b29/6148a37b672cd95c8f2e8ee4_BFD_Background.jpg)] bg-cover bg-[50%_100%] bg-no-repeat w-full min-h-[600px]" />
  );
};

export default HeroParralax;
