/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TextBlockProps {
  text: string;
}

export const TextBlock: React.FC<TextBlockProps> = ({ text }) => (
  <p className="mt-4 w-full text-base font-light max-md:max-w-full">{text}</p>
);
