/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LatestEpisodes from "./LatestEpisode";
import BlurFade from "@/components/magicui/blur-fade";

const LatestEpisodesWrapper: React.FC = () => {
  return (
    <main className="flex flex-col items-center bg-red-100 ">
      <div className="flex flex-col w-full max-md:px-5 max-w-7xl lg:max-w-[1400px]">
        <BlurFade>
          <div className="grid grid-cols-3 gap-5 justify-center px-5 pt-5 w-full max-md:max-w-full">
            <img
              
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/22849bc68bee22d0f37ec5d7ea186d92812c4217dcca6a025f7d8ec08a2a1949?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a"
              alt=""
              className="object-contain w-full max-w-md max-md:hidden"
            />

            <div className="col-span-full md:col-span-2">
              <LatestEpisodes />
            </div>
          </div>
        </BlurFade>
      </div>
    </main>
  );
};

export default LatestEpisodesWrapper;
