/**
 * This code was generated by Builder.io.
 */
import React from "react";
import EpisodeItem from "./EpisodeItem";
import { Button } from "@/components/ui/button";

interface Episode {
  number: string;
  title: string;
  imageSrc: string;
}

const episodes: Episode[] = [
  {
    number: "",
    title:
      "Generational Healing of Trauma Can Only Happen With God",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/94ee757f1db37c983507b059bd07c87a767cef8c19ffbf9eec5262fbee82895c?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
  },
  {
    number: "",
    title: "Do This Every Morning To Stop Procrastination & Never Be Lazy",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/94ee757f1db37c983507b059bd07c87a767cef8c19ffbf9eec5262fbee82895c?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
  },
  {
    number: "",
    title: "How I Manage My Time — 5 Tips To Win At Anything In Life",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/94ee757f1db37c983507b059bd07c87a767cef8c19ffbf9eec5262fbee82895c?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
  },
  {
    number: "",
    title: "This Conversation Could Save Your Relationship | Harville & Helen",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/94ee757f1db37c983507b059bd07c87a767cef8c19ffbf9eec5262fbee82895c?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
  },
  {
    number: "",
    title: "The Best Anti-Aging Advice for Women Over 40 (Wish I Knew Sooner)",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/94ee757f1db37c983507b059bd07c87a767cef8c19ffbf9eec5262fbee82895c?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
  },
];

const LatestEpisodes: React.FC = () => {
  return (
    <section className="bg-ramsha-accent">
      <section className="flex flex-col grow shrink items-center pt-10 pb-12 w-3/5 ml-auto mr-[80px]">
        <h2 className="pt-6 pb-3 text-xs font-extrabold leading-5 uppercase text-neutral-800 tracking-[2.16px]">
          KEYNOTE SPEAKER TOPICS
        </h2>
        <div className="flex flex-col items-end pb-10">
          {episodes.map((episode, index) => (
            <EpisodeItem key={index} {...episode} />
          ))}
        </div>
        <button
          className="text-white shadow-none hover:shadow-none bg-black rounded-full px-6 pt-2.5 pb-3 text-base font-bold text-center hover:bg-black/85 "
        >
          <a
            href="https://www.marieforleo.com/podcast"
            target="_blank"
            rel="noopener noreferrer"
          >
            View All Episodes
          </a>
        </button>
      </section>
    </section>
  );
};

export default LatestEpisodes;
