/**
 * This code was generated by Builder.io
 */
import React from "react";
import SecurePayment from "./SecurePayment";

interface PricingCardProps {
  type: string;
  price: string;
  period: string;
  buttonText: string;
  highlightText: string;
  highlightColor: string;
}

const PricingCard: React.FC<PricingCardProps> = ({
  type,
  price,
  period,
  buttonText,
  highlightText,
  highlightColor,
}) => {
  return (
    <div className="flex flex-col grow shrink items-center min-w-[240px] w-[333px]">
      <div className="flex flex-col flex-1 items-center px-8 pt-11 pb-20 bg-white rounded-3xl border border-gray-200 border-solid shadow-sm max-w-[1000px] w-[417.6px] max-md:px-5">
        <div className="flex flex-col pb-8 text-xs tracking-normal leading-5 text-neutral-500">
          <div
            className={`flex flex-col justify-center items-center px-2.5 py-1 ${highlightColor} rounded-md`}
          >
            <div>{highlightText}</div>
          </div>
        </div>
        <div className="flex flex-col pt-6 text-sm font-bold tracking-widest leading-6 uppercase text-neutral-800">
          <div>{type}</div>
        </div>
        <div className="text-4xl font-bold tracking-wide whitespace-nowrap leading-[54px] text-neutral-800">
          {price}
          <span className="text-2xl">{period}</span>
        </div>
        <div className="flex flex-col self-stretch pb-2.5 mt-10 mr-5 ml-5 text-2xl font-bold tracking-wide leading-6 text-center text-white min-w-[275px] max-md:mx-2.5">
          <button className="px-24 py-5 bg-green-500 min-w-[275px] rounded-[200px] max-md:px-5">
            {buttonText}
          </button>
        </div>
        <SecurePayment />
        <div className="flex flex-col self-stretch pt-5">
          <img
            
            src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/18e8dc230da1ba7dcd86b152badac1f130fbf0034ab6e77a6fdb247d2e95d6d5?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
            alt=""
            className="object-contain w-full aspect-[9.8]"
          />
        </div>
      </div>
    </div>
  );
};

export default PricingCard;
