/**
 * This code was generated by Builder.io
 */
import React from "react";
import Image from "next/image";

const SecurePayment: React.FC = () => {
  return (
    <div className="flex z-10 flex-col pt-2.5">
      <div className="flex justify-center items-center">
        <div className="flex flex-col items-start self-stretch pr-1.5 my-auto max-w-[158px] w-[17px]">
          <Image
            src="https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/7a9c77befcadda052058f632bce5a989106cae481150bb87eb96f834dc6cd419?apiKey=48a1608e30b648c89bd5ed134a49b3b8&"
            alt=""
            className="object-contain w-3 aspect-[0.86]"
            width={17}
            height={20}
          />
        </div>
        <div className="self-stretch my-auto text-xs tracking-normal leading-5 text-neutral-500">
          Encrypted Secure Payment
        </div>
      </div>
    </div>
  );
};

export default SecurePayment;
