/**
 * This code was generated by Builder.io
 */
import React from "react";

const Details: React.FC = () => {
  return (
    <div className="max-w-[1200px] mx-auto px-6 py-12 bg-ramsha-accent">
      <h1 className="text-[72px] font-seasons mb-6">Privacy Policy</h1>
      
      <div className="space-y-8 text-lg">
        <section>
          <p>
            We are committed to maintaining the accuracy, security and privacy of Personal Information in accordance with applicable legislation. Please review the following policy to learn about our privacy policies. By accessing this website you consent to the policies herein.
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Who We Are</h2>
          <p>
            The owner and operator of this website is IQRA DREAM INC, DBA GLOWING FEMME. (Hereinafter referred to as IQRA DREAM INC, We, or Us).
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Personal Information</h2>
          <p>
            By providing us with your personal information, you consent to the collection, use and disclosure of that information as described in this Policy.
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Types of Information</h2>
          <p>
            The types of personal information we may collect about you includes, but may not be limited to, your name, contact information, billing information, credit card information, account information, address, billing and delivery information, telephone number, email address, IP address, financial account information, information relevant to your business, your opinion, other information related to your business and services, other data collected that could directly or indirectly identify you, and other information as you may wish to input through this web site.
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Use of Personal Information</h2>
          <p>
            We collect and use your personal information to operate this Web Site and deliver the services and information you have requested, as well as other purposes that may be indicated to you at the time you provide your personal information. Such use of your personal information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-6 mt-4 space-y-2">
            <li>For the purpose of facilitating payment</li>
            <li>We use information regarding your location to provide a customized experience</li>
            <li>We may use cookies to provide a customized experience</li>
            <li>To facilitate communication between parties</li>
            <li>To provide you access to the products and / or services you request</li>
            <li>To communicate in general</li>
            <li>To respond to comments and / or questions</li>
            <li>To improve our service and / or products</li>
            <li>To notify you of product / services that may be of interest to you</li>
            <li>To request information from you</li>
            <li>To provide other information to you</li>
            <li>To collect fees</li>
            <li>To tailor content, advertising & marketing to you</li>
            <li>To publish articles that provide information to site users</li>
            <li>Any testimonials and / or reviews we receive may be published, using your name</li>
            <li>Testimonials and / or reviews of both positive and negative and or / unflattering nature</li>
          </ul>
        </section>

        <section>
          <h2 className="font-bold mb-4">Data Storage</h2>
          <p>
            You acknowledge and agree that data held may be transferred from your current location to our offices and servers and authorized third parties referred to in this Privacy Policy located in the United States.
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Sharing of Personal Information</h2>
          <p>We may share information with the following:</p>
          <ul className="list-disc pl-6 mt-4 space-y-2">
            <li>Our Partners – in order to provide promotions and other services that may interest you.</li>
            <li>Third Party Vendors – who provide services on our behalf.</li>
            <li>Mentors – including guest speakers, or presenters, who we believe may be of interest to you.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-bold mb-4">Other</h2>
          <p>
            We may share personal information in response to a request from a judicial authority. Such disclosure may be outside of any jurisdiction that you are present in. We may waive any defense available to us. We may share personal information in connection with a corporate transaction such as a merger, take over, etc. We may share aggregate and or anonymous information with 3rd parties for other purposes including but not limited to promotion, marketing, investment solicitations, etc.
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Contact Information</h2>
          <p>Email: team@glowingfemme.com</p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Modifications</h2>
          <p>
            We reserve the right to modify or supplement this Privacy Policy at any time, without prior notice, you agree to be bound by such modifications and or supplements.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Details;
