/**
 * This code was generated by Builder.io
 */
import React from "react";
import { TextContainer } from "./TextContainer";
import { Heading } from "./Heading";

interface DreamClubHeroProps {
  introText: string[];
  headingText: string[];
  contentText: string[];
}

const DreamClubHero: React.FC<DreamClubHeroProps> = ({
  introText,
  headingText,
  contentText,
}) => {
  return (
    <section className="flex flex-col text-base font-light leading-7 text-black max-w-[915px]">
      <TextContainer paragraphs={introText} />
      <Heading text={headingText} />
      <TextContainer paragraphs={contentText} />
    </section>
  );
};

export default DreamClubHero;