/**
 * This code was generated by Builder.io
 */
import React from "react";
import TestimonialCard from "./TestimonialCard";

interface Testimonial {
  imageSrc: string;
  quote: string;
  author: string;
}

const testimonials: Testimonial[] = [
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/1ecdb0af001fec455004ac19dc6383d6c0a8fcfb3d83ce9771a9b8d77aa451f6?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    quote:
      "I'm still the same person, but I've LEVELED UP SO MUCH. I'm so happy with my life and business I could literally cry.",
    author: "Celestine F.",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/e7ec5498ca687178cec2aa1882696ceaeafda0b09b2550234b4923589acac72a?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    quote:
      "Marie walks the talk. She does what she teaches! Not only do you get awesome tips and learning, you get to watch the Master in Action!",
    author: "Krista S.",
  },
  {
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/a35262e4648841219ed0a1388db4ae3ebd000c7854b3f16bc444a4878c9f794b?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    quote:
      "Marie Forleo and team, you were the catalysts for getting my ass in gear after seven long years of dreaming the entrepreneurial dream.",
    author: "Callie G.",
  },
];

const TestimonialSection: React.FC = () => {
  return (
    <section className="flex flex-col items-center">
      <div className="flex flex-col justify-center items-center p-20 w-full max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col w-full max-w-[800px] max-md:max-w-full">
          {testimonials.map((testimonial, index) => (
            <TestimonialCard
              key={index}
              imageSrc={testimonial.imageSrc}
              quote={testimonial.quote}
              author={testimonial.author}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default TestimonialSection;
