/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroContent from "./HeroContent";
import HeroImage from "./HeroImage";

const HeroSection: React.FC = () => {
  return (
    <section className="flex flex-col md:flex-row max-lg:px-8 max-md:px-5">
      <div className="w-full md:w-1/2 pb-10">
        <HeroContent />
      </div>
      <div className="w-full md:w-1/2">
        <HeroImage />
      </div>
    </section>
  );
};

export default HeroSection;
