/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button as ShadcnButton } from "@/components/ui/button";

interface ButtonProps {
  className?: string;
  href?: string;
  text: string;
}

const Button: React.FC<ButtonProps> = ({ className = '', href, text }) => {
  return (
    <ShadcnButton className="font-subheader tracking-wider font-[900] w-full lg:max-w-[300px] whitespace-nowrap lg:px-4 xl:px-8 py-3 text-sm lg:text-base text-center text-white capitalize bg-ramsha-tertiary hover:bg-ramsha-tertiary/90 rounded-md transition-all duration-300 overflow-hidden">
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
      >
        {text}
      </a>
    </ShadcnButton>
  );
};

export default Button;