/**
 * This code was generated by Builder.io.
 */
import { motion } from "framer-motion";
import React from "react";
import Button from "./Button";

interface SecondaryButtonProps {
  className?: string;
  href?: string;
  text: string;
}

const SecondaryButton: React.FC<SecondaryButtonProps> = ({ className = '', href, text }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.4 }}
      viewport={{ once: true }}
    >
      <Button href={href} text={text} />
    </motion.div>
  );
};

export default SecondaryButton;