/**
 * This code was generated by Builder.io
 */
import React from "react";

interface SectionContentProps {
  title: string;
  subtitle?: string;
  content: string;
  additionalInfo?: string;
  imageSrc: string;
  imageAlt: string;
}

export const SectionContent: React.FC<SectionContentProps> = ({
  title,
  subtitle,
  content,
  additionalInfo,
  imageSrc,
  imageAlt,
}) => {
  return (
    <>
      <div className="flex flex-col grow shrink justify-center items-center self-start py-6 max-w-[900px] min-h-[638px] min-w-[240px] w-[318px]">
        <div className="flex flex-col pb-2 max-w-full text-xl font-light tracking-wide leading-8 text-neutral-800 w-[397px]">
          <div className="flex flex-col items-center px-5">
            <h3 className="text-2xl font-bold">{title}</h3>
            {subtitle && <p>{subtitle}</p>}
          </div>
        </div>
        <div className="flex flex-col pt-2 max-w-full text-base font-light tracking-normal w-[391px]">
          <div className="flex flex-col w-full">
            <p className="w-full italic leading-7">{content}</p>
            {additionalInfo && (
              <div className="flex flex-col items-center px-2.5 mt-4 w-full leading-6">
                <p className="italic">{additionalInfo}</p>
              </div>
            )}
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-contain grow shrink aspect-[0.62] min-w-[240px] w-[317px]"
      />
    </>
  );
};
