/**
 * This code was generated by Builder.io
 */
import React from "react";

export const SectionHeading: React.FC = () => {
  return (
    <div className="flex flex-col self-center pt-4 w-full text-center max-w-[775px]">
      <h2 className="pr-10 pl-10 w-full text-4xl  leading-[54px] text-neutral-800 max-md:px-5 max-md:max-w-full">
        Dream Club Members Can Expect More Sales, More Profit, and More Freedom.{" "}
        <span className="italic text-neutral-800">
          But That&apos;s Just The Start…{" "}
        </span>
      </h2>
      <div className="flex flex-col pb-4 px-6 mt-8 w-full text-base font-light tracking-normal leading-7 text-black max-md:max-w-full">
        <p className=" w-full max-md:px-5 max-md:max-w-full">
          Most memberships drown you with piles of watered-down, pre-recorded
          content to create &apos;perceived value.&apos; That makes us want to
          take a (hard) nap.
        </p>
        <p className="mt-4 w-full max-md:px-5 max-md:max-w-full">
          You&apos;ve already got too much on your plate! Nobody has time to
          sift through countless videos, audios, worksheets, and trainings.
        </p>
        <p className="mt-4 w-full max-md:px-5 max-md:max-w-full">
          That&apos;s why in Dream Club,{" "}
          <span className="font-bold text-black">
            our calendar is intentionally s p a c i o u s and results-focused.{" "}
          </span>
        </p>
        <p className="mt-4 w-full max-md:px-5 max-md:max-w-full">
          Here is just a taste of our monthly masterclasses:
        </p>
      </div>
    </div>
  );
};
