/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TestimonialBoxProps {
  testimonial: string;
  author: string;
}

export const TestimonialBox: React.FC<TestimonialBoxProps> = ({
  testimonial,
  author,
}) => {
  return (
    <div className="flex flex-col pt-8 pb-6 text-xs tracking-normal leading-5">
      <div className="p-3 bg-gray-200 rounded-xl">
        "{testimonial}" — {author}
      </div>
    </div>
  );
};
