/**
 * This code was generated by Builder.io.
 */
import React from "react";
import VideoButton from "./VideoButton";
import BlurFade from "@/components/magicui/blur-fade";
import Image from "next/image";

const HeroSection: React.FC = () => {
  return (
    <section className="relative flex flex-col justify-center items-start bg-black w-full">
      <div className="absolute inset-0 bg-black opacity-50 z-10" />
      
      <div className="flex overflow-hidden z-0 flex-col flex-1 self-stretch w-full">
        <Image
          src="/hero.webp"
          alt="Background image"
          className="object-cover w-full h-full md:object-contain md:aspect-[1.78] max-md:aspect-square"
          width={1920}
          height={1080}
          priority
          quality={100}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 100vw"
        />
      </div>

      <div className="absolute basis-full inset-0 z-20 flex flex-col h-full items-center w-full">
        <BlurFade className="h-full">
          <div className="h-full flex flex-col items-center pt-10 xl:pt-14 w-full max-md:px-5 font-montserrat-bold">
            <h1 className="uppercase text-white text-center tracking-normal sm:tracking-wider w-full max-md:px-0 max-md:max-w-full text-3xl sm:text-3xl 2xl:text-9xl xl:text-7xl lg:text-7xl md:text-5xl 2xl:leading-[160px] xl:leading-[80px] lg:leading-[60px] md:leading-[50px] leading-[35px]">
              Let Go Let God
            </h1>
            <h1 className="uppercase text-white text-center tracking-normal sm:tracking-wider w-full max-md:px-0 max-md:max-w-full text-3xl sm:text-3xl 2xl:text-9xl xl:text-7xl lg:text-7xl md:text-5xl 2xl:leading-[320px] xl:leading-[170px] lg:leading-[120px] md:leading-[100px] leading-[70px]">
              A Global Revolution
            </h1>
          </div>
        </BlurFade>
      </div>
    </section>
  );
};

export default HeroSection;
