/**
 * This code was generated by Builder.io.
 */
import React from "react";
import VideoButton from "./VideoButton";
import BlurFade from "@/components/magicui/blur-fade";
import Image from "next/image";

const HeroSection: React.FC = () => {
  return (
    // <BlurFade yOffset={10}>
    //   <section className="bg-stone-50 relative flex flex-col justify-center items-start bg-black w-full max-md:h-[600px] md:h-screen max-h-[810px]">
    //     <div className="flex overflow-hidden z-0 flex-col flex-1 self-stretch w-full h-full">
    //       <Image
    //         src="/hero.svg"
    //         alt="Background image"
    //         className="object-cover w-full h-full"
    //         width={1920}
    //         height={1080}
    //         priority
    //         quality={100}
    //         sizes="100vw"
    //       />
    //     </div>
    //   </section>
    // </BlurFade>
    <section className="relative flex flex-col justify-center items-start bg-black w-full">
      <div className="absolute inset-0 bg-black opacity-50 z-10" />
      
      <div className="flex overflow-hidden z-0 flex-col flex-1 self-stretch w-full">
        <Image
          src="/hero.svg"
          alt="Background image"
          className="object-contain w-full aspect-[1.78] max-md:max-w-full"
          width={1920}
          height={1080}
          priority
          quality={100}
          sizes="100vw"
        />
      </div>

      <div className="absolute basis-full inset-0 z-20 flex flex-col justify-center h-full items-center w-full">
        <BlurFade className="h-full">
          <div className="h-full flex flex-col items-center justify-center w-full max-md:px-5">
            <h1 className="uppercase text-ramsha-accent text-center tracking-normal w-full max-md:px-0 max-md:max-w-full text-3xl 2xl:text-9xl xl:text-7xl lg:text-5xl md:text-5xl 2xl:leading-[320px] xl:leading-[170px] lg:leading-[120px] md:leading-[100px] leading-[70px] font-montserrat">
              Let Go Let God
            </h1>
            <h1 className="uppercase text-ramsha-accent text-center tracking-normal w-full max-md:px-0 max-md:max-w-full text-3xl 2xl:text-9xl xl:text-7xl lg:text-5xl md:text-5xl 2xl:leading-[320px] xl:leading-[170px] lg:leading-[120px] md:leading-[100px] leading-[70px] font-montserrat">
              A Global Revolution
            </h1>
          </div>
        </BlurFade>
      </div>
    </section>
  );
};

export default HeroSection;
