/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageComponentProps {
  src: string;
  alt: string;
}

const ImageComponent: React.FC<ImageComponentProps> = ({ src, alt }) => {
  return (
    <img
      
      src={src}
      alt={alt}
      className="object-cover w-full h-[250px] md:h-[438px]"
    />
  );
};

export default ImageComponent;
