/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

interface ImageComponentProps {
  src: string;
  alt: string;
}

const ImageComponent: React.FC<ImageComponentProps> = ({ src, alt }) => {
  return (
    <Image
      src={src}
      alt={alt}
      className="object-cover w-full h-[250px] md:h-[438px]"
      width={500}
      height={438}
    />
  );
};

export default ImageComponent;
