/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageComponent from "./ImageComponent";

const MainComponent: React.FC = () => {
  return (
    <main>
      <section className="relative -mb-32">
        <ImageComponent
          src="/ramsha-pics/webp/hero-background.webp"
          alt="Main content image"
        />
      </section>
    </main>
  );
};

export default MainComponent;
