/**
 * This code was generated by Builder.io
 */
import React from "react";
import QuizCard from "./QuizCard";

const EntrepreneurQuiz: React.FC = () => {
  const quizData = [
    {
      title: "What Type of Entrepreneur Are You?",
      subtitle: "Free Quiz",
      description:
        "Discover the special gift that only you have. Get your personalized success plan to create a business and life you love.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/c9a0dc5dcf68fb46a5b99dbe57b5f985a57773164099a8ee5308e15836ee7a57?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      buttonText: "Take Free Quiz",
    },
    {
      title: "Want to Earn More by Working Less?",
      subtitle: "Free Quiz",
      description:
        "Discover your unique Time Stress Type and get a FREE custom action plan to take back your time, money, & life.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/d3d5becdeebb7e794c228920222e963c9183eec47c457a3b38ec6f170dd14e42?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
      buttonText: "Take Free Quiz",
    },
  ];

  return (
    <main className="flex flex-col text-base max-w-[916px] text-neutral-800">
      {quizData.map((quiz, index) => (
        <QuizCard
          key={index}
          title={quiz.title}
          subtitle={quiz.subtitle}
          description={quiz.description}
          imageSrc={quiz.imageSrc}
          buttonText={quiz.buttonText}
        />
      ))}
    </main>
  );
};

export default EntrepreneurQuiz;
