/**
 * This code was generated by Builder.io
 */
import React from "react";

const Details: React.FC = () => {
  return (
    <div className="max-w-[1200px] mx-auto px-6 pt-10 pb-16">
      <h1 className="text-[72px] font-header mb-6">Contact Us</h1>
      
      <div className="space-y-8 text-lg">
        <section>
          <h2 className="font-bold mb-4">Get in Touch</h2>
          <p>
            We'd love to hear from you! Whether you have questions about our programs, need support, or want to share feedback, our team is here to help.
          </p>
        </section>

        <section>
          <h2 className="font-bold mb-4">Contact Information</h2>
          <div className="space-y-4">
            <p>
              <strong>Email:</strong> teamgf@glowingfemme.com
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-bold mb-4">Frequently Asked Questions</h2>
          <div className="space-y-4">
            <div>
              <h3 className="font-semibold">How can I join a program?</h3>
              <p>
                Visit our Programs page to see current offerings and join our waitlist for upcoming cohorts.
              </p>
            </div>
            <div>
              <h3 className="font-semibold">What payment methods do you accept?</h3>
              <p>
                We process all payments through Stripe.
              </p>
            </div>
            <div>
              <h3 className="font-semibold">Can I get a refund?</h3>
              <p>
                Please review our Refund Policy or contact us directly to discuss your specific situation.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="font-bold mb-4">Media Inquiries</h2>
          <p>
            For press and media inquiries, please email us at teamgf@glowingfemme.com
          </p>
        </section>
      </div>
    </div>
  );
};

export default Details;
