/**
 * This code was generated by Builder.io
 */
'use client'

import * as React from "react";
import { motion } from "framer-motion";
import Image from "next/image";

interface HeroTextProps {
  text: string;
  isHighlighted?: boolean;
  delay?: number;
}

interface HeroSectionProps {
  texts: Array<{ text: string; isHighlighted?: boolean }>;
}

const HeroText: React.FC<HeroTextProps> = ({ text, isHighlighted, delay = 0 }) => (
  <motion.span 
    initial={{ opacity: 0, y: 20 }}
    whileInView={{ opacity: 1, y: 0 }}
    transition={{ 
      duration: 0.8,
      delay: delay,
      ease: [0.22, 1, 0.36, 1]
    }}
    viewport={{ once: true }}
    className={`${isHighlighted ? "italic" : ""} text-white font-serif inline-block`}
  >
    {text}
  </motion.span>
);

const HeroSection: React.FC<HeroSectionProps> = ({ texts }) => {
  return (
    <main className="relative w-full min-h-screen">
      {/* Background Image */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1.2 }}
        className="absolute inset-0"
      >
        <Image
          src="/gridImages/image30.webp"
          alt="Interior with wooden stairs and dining area"
          fill
          className="object-cover brightness-125"
          priority
          sizes="100vw"
          quality={100}
        />
        <div className="absolute inset-0 bg-gradient-to-r from-black/30 to-transparent" />
      </motion.div>

      {/* Content */}
      <div className="relative z-10 flex items-center min-h-screen">
        <section className="container flex flex-col mx-auto px-4">
          {/* White divider line */}
          
          <h1 className="text-5xl leading-tight max-w-xl font-serif relative">
            {texts.map((item, index) => (
              <React.Fragment key={index}>
                <HeroText
                  text={item.text}
                  isHighlighted={item.isHighlighted}
                  delay={0.5 + (index * 0.2)}
                />
                {index < texts.length - 1 && index !== 0 && " "}
                {index === 0 && <br />}
              </React.Fragment>
            ))}
          </h1>
          <div className="w-1/2 mt-10 h-[1px] bg-white/50" />
        </section>
      </div>
    </main>
  );
};

export default HeroSection;
