/**
 * This code was generated by Builder.io
 */
import React from "react";

interface BackgroundBorderProps {
  children: React.ReactNode;
}

const BackgroundBorder: React.FC<BackgroundBorderProps> = ({ children }) => {
  return (
    <div className="flex flex-col flex-1 px-12 py-8 w-full rounded-2xl border border-black border-solid bg-stone-50 max-md:px-5 max-md:max-w-full">
      {children}
    </div>
  );
};

export default BackgroundBorder;
