/**
 * This code was generated by Builder.io
 */
import React from "react";

const BottomContent: React.FC = () => {
  return (
    <div className="flex flex-col mt-4 text-base max-md:max-w-full">
      <p className="font-light italic">
        &quot;But Ramsha,&quot;{" "}
        <span className="not-italic text-black">you might be thinking,</span>
        &quot;Alhamdulillah, I'm grateful for my life as it is. Perhaps I should be content with what Allah has given me.&quot;
      </p>

      <p className="mt-4 font-light max-md:max-w-full">
        My beloved sister, while gratitude (shukr) is beautiful, remember that Allah calls us to manifest our highest potential. There's a profound difference between gratitude and limiting your divine purpose.
      </p>

      <p className="mt-4 font-light max-md:max-w-full">
        When you disconnect from your divine feminine essence, you're not just affecting your own spiritual journey. Your family, community, and the entire ummah miss out on the light Allah meant for you to share.
      </p>

      <ul className="list-disc ml-10 mt-4 font-light">
        <li className="w-full max-md:max-w-full">
          Your children miss experiencing a mother fully connected to her spiritual power
        </li>
        <li className="mt-2 w-full text-black max-md:max-w-full">
          That divine inspiration to write a book that could guide countless sisters remains
          <span className="italic text-black"> unmanifested</span>
        </li>
        <li className="mt-2 w-full text-black max-md:max-w-full">
          Your spiritual practices feel rushed, leaving your soul yearning for deeper
          <span className="italic"> connection</span>
        </li>
      </ul>

      <p className="mt-4 font-light max-md:max-w-full">
        SubhanAllah, your presence here is a sign from Allah. You're ready for more spiritual abundance, divine connection, and soul-deep fulfillment.
      </p>

      <p className="mt-4 font-light max-md:max-w-full">But how do you begin this sacred journey?</p>

      <p className="mt-4 font-bold max-md:max-w-full">You could:</p>

      <ul className="flex overflow-hidden flex-col pb-2 pl-10 mt-4 font-light max-md:pl-5 max-md:max-w-full list-disc">
        <li className="w-full text-base max-md:max-w-full">
          Continue collecting Islamic self-help books without deep implementation
        </li>
        <li className="mt-2 w-full max-md:max-w-full">
          Invest in surface-level solutions that don't address your soul's true needs
        </li>
        <li className="mt-2 w-full max-md:max-w-full">
          Attend another general spiritual retreat that doesn't understand your unique journey as a Muslim woman
        </li>
      </ul>

      <p className="mt-4 font-light max-md:max-w-full">
        You can continue seeking answers alone on your spiritual path...
      </p>

      <p className="mt-4 font-light text-black max-md:max-w-full">
        OR you can join our sacred sisterhood of spiritually aligned Muslimahs who are committed to living their divine purpose
        <span className="italic"> authentically</span>.
      </p>

      <div className="flex flex-col items-center max-w-full font-light text-center max-md:px-5">
        <div className="flex flex-col pt-6 pb-4 w-full">
          <p className="text-2xl tracking-wide leading-8 text-neutral-800 max-md:px-5 max-md:max-w-full max-w-[707px] mx-auto">
            We are divinely guided sisters who
            <span className="italic"> embrace </span>
            our feminine power while honoring our deen.
          </p>
          <p className="px-1 mt-2 w-full text-lg tracking-normal leading-8 text-black max-md:max-w-full max-w-3xl mx-auto">
            <span className="text-black">We are </span>
            <span className="font-bold text-black">spiritually aligned</span>
            <span className="text-black"> women, </span>
            <span className="font-bold text-black">devoted</span>
            <span className="text-black"> to our growth, </span>
            <span className="font-bold text-black">committed</span>
            <span className="text-black"> to reaching new</span>
            <br />
            <span className="text-black">
              levels of spiritual abundance and authentic freedom — together, bi'ithnillah.
            </span>
          </p>
        </div>
      </div>
    </div>
  );
};

export default BottomContent;
