/**
 * This code was generated by Builder.io
 */
import React from "react";

const Emphasis: React.FC = () => {
  return (
    <div className="flex flex-col pb-1 mt-4 max-md:max-w-full">
      <p className="text-base italic font-light max-md:max-w-full">
        <span className="text-black">You've worked </span>
        <span className="italic text-black">so</span>
        <span className="text-black">
          {" "}
          hard to create the best business, health, and relationships possible.
        </span>
      </p>
      <div className="flex flex-col py-1 max-w-full w-[809px]">
        <p className="self-end text-base font-bold">Yet, despite your</p>
        <p className="self-start mt-3.5 text-base italic font-bold max-md:max-w-full">
          <span className="text-black">
            efforts, you're still just scratching the surface of where you{" "}
          </span>
          <span className="italic text-black">know</span>
          <span className="text-black"> you could be.</span>
        </p>
      </div>
    </div>
  );
};

export default Emphasis;
