/**
 * This code was generated by Builder.io
 */
import React from "react";

const Heading: React.FC = () => {
  return (
    <header className="flex flex-col pt-6 pb-2 w-full text-2xl tracking-wide leading-8 text-center text-neutral-800 max-md:max-w-full">
      <div className="flex flex-col pr-28 pl-28 w-full max-md:px-5 max-md:max-w-full">
        <h2 className="self-center font-light max-md:max-w-full">
          Now, pause for a moment and ask yourself…
        </h2>
        <h3 className="flex-1 shrink w-full italic font-bold max-md:max-w-full">
          <span className="text-neutral-800">
            What is settling for the status quo{" "}
          </span>
          <span className="italic text-neutral-800">truly</span>
          <span className="text-neutral-800"> costing you?</span>
        </h3>
      </div>
    </header>
  );
};

export default Heading;
