/**
 * This code was generated by Builder.io
 */
import React from "react";

const listItems = [
  "Attended all the seminars, conferences, and networking events, only to find they lack lasting impact.",
  "Poured your heart into countless courses, hired coaches, and gone to therapy, but still aren't where you want to be.",
  "Experimented with bodywork, diets, and fitness plans that haven't delivered more than a temporary fix.",
  "Collected shelves full of self-help, business, and personal development books, without learning how to turn knowledge into action.",
  "Explored everything from mindfulness to micro-dosing in pursuit of wellness, yet still haven't unlocked your full creative and emotional potential.",
];

const List: React.FC = () => {
  return (
    <ul className="list-disc ml-10 font-light">
      {listItems.map((item, index) => (
        <li
          key={index}
          className={`w-full max-md:max-w-full${index > 0 ? " mt-2" : ""}`}
        >
          {item}
        </li>
      ))}
    </ul>
  );
};

export default List;
