/**
 * This code was generated by Builder.io
 */
import React from "react";

const TextContent: React.FC = () => {
  return (
    <div className="flex flex-col pt-2 w-full tracking-normal leading-7 text-black max-md:max-w-full">
      <div className="flex flex-col pb-4 w-full max-md:max-w-full">
        <p className="text-base font-light max-md:max-w-full">
          Maybe you've grown accustomed to the daily grind and exhaustion,
          telling yourself you're managing just <br />
          fine. That this is "just how it is."
        </p>
        <p className="mt-4 text-base italic font-light max-md:max-w-full">
          <span className="text-black">
            But, if you're like most people, you've already spent{" "}
          </span>
          <span className="italic text-black">thousands</span>
          <span className="text-black">
            {" "}
            of dollars trying to "get ahead" in{" "}
          </span>
          <br />
          <span className="text-black">business and life. You've…</span>
        </p>
      </div>
    </div>
  );
};

export default TextContent;
