/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface LinkItem {
  text: string;
  href: string;
}

const companyLinks: LinkItem[] = [
  { text: "About", href: "#" },
  { text: "RamshaTV", href: "https://www.ramshasuhail.com/ramshatv" },
  {
    text: "The Ramsha Forleo Podcast",
    href: "https://www.ramshasuhail.com/podcast",
  },
  {
    text: "Success Stories",
    href: "https://www.ramshasuhail.com/success-stories",
  },
  { text: "New Here?", href: "https://www.ramshasuhail.com/new-here" },
  { text: "Free Tools", href: "https://www.ramshasuhail.com/free-tools" },
  { text: "Press & Media", href: "https://www.ramshasuhail.com/press-media" },
  { text: "Giving Back", href: "https://www.ramshasuhail.com/giving-back" },
  { text: "How We Roll", href: "https://www.ramshasuhail.com/how-we-roll" },
  { text: "Jobs", href: "https://www.ramshasuhail.com/jobs" },
];

const CompanyLinks: React.FC = () => {
  return (
    <nav className="flex flex-col grow shrink px-2.5 pt-6 pb-20 min-h-[1px] min-w-[240px] w-[323px]">
      <h2 className="pb-px text-xs font-extrabold leading-5 text-white uppercase whitespace-nowrap tracking-[2.16px]">
        Company
      </h2>
      <ul className="mt-3">
        {companyLinks.map((link, index) => (
          <li
            key={index}
            className="flex flex-col items-start pb-1 w-full text-sm tracking-wide leading-7 text-white"
          >
            <a href={link.href} target="_blank" rel="noopener noreferrer">
              {link.text}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default CompanyLinks;
