/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProgramLogin: React.FC = () => {
  return (
    <div className="overflow-hidden px-24 pt-2.5 pb-3 mt-7 max-w-full text-base font-bold tracking-wide leading-6 text-center text-white capitalize rounded-3xl bg-white bg-opacity-0 w-[300px] max-md:px-5">
      <a
        href="https://programs.ramshasuhail.com/"
        target="_blank"
        rel="noopener noreferrer"
      >
        program login
      </a>
    </div>
  );
};

export default ProgramLogin;
