/**
 * This code was generated by Builder.io
 */
import React from "react";
import MediaMentions from "./MediaMentions";

const logos = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/47eacb56c0799f691ebdde76461eaf3c5a947e62705ea4ba043680d3d0c5a4c0?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 1",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/64c0b822918b9532689abaae2274a2862612ab0458a883d564de465edced3167?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 2",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/5f00e1f82ea03dc41f0f8049cd02d9f9fa20d70882a21ee951323d4f232384b9?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 3",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/062a8da3082a8733d7bb643bad05269a5c6a0a95315c2980095ce24cf70a806e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 4",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/ad28b199078a670b422095ba343b4fe6756c421fd21669e41a2791d02e8909b2?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 5",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/94f701e4656b7fc8e76e9aef3d9f1b33dbdd250af5bb559e11fc6aa1a790302e?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 6",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/73603fe92f9bf4b095cf6b19b401766a59ac53a003190eafd3509227a0984305?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 7",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/aaab7a99da308e79bfeeedc8362a1efc4213ad8eb1e0bf58ad241874fb8caf38?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 8",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/48a1608e30b648c89bd5ed134a49b3b8/3bcd253bd03bcac8d3e79b68b6d1f556c2b8fd0b3643725253e7602721c31d9b?apiKey=48a1608e30b648c89bd5ed134a49b3b8&",
    alt: "Media Logo 9",
  },
];

const MediaMentionsSection: React.FC = () => {
  return <MediaMentions logos={logos} />;
};

export default MediaMentionsSection;
