/**
 * This code was generated by Builder.io
 */
import React from "react";

interface ResourceCardProps {
  imageSrc: string;
  title: string;
  description: string;
  ctaText: string;
  ctaLink?: string;
}

const ResourceCard: React.FC<ResourceCardProps> = ({
  imageSrc,
  title,
  description,
  ctaText,
  ctaLink,
}) => {
  return (
    <article className="flex flex-col grow shrink pb-2 min-w-[240px] w-[212px]">
      <div className="flex items-center">
        <img
          loading="lazy"
          src={imageSrc}
          alt={title}
          className="object-contain self-stretch my-auto aspect-square max-w-[265px] min-w-[240px] w-[265px]"
        />
      </div>
      <h2 className="flex justify-center items-start pt-5 pb-2 text-lg tracking-wide leading-7 text-neutral-800">
        <span className="flex-1 shrink w-full min-w-[240px]">{title}</span>
      </h2>
      <p className="pb-px text-xs tracking-normal leading-5 text-black">
        {description}
      </p>
      {ctaLink ? (
        <a
          href={ctaLink}
          target="_blank"
          rel="noopener noreferrer"
          className="overflow-hidden self-start px-4 py-2.5 mt-4 text-xs font-extrabold tracking-widest leading-4 text-center text-black uppercase rounded-3xl bg-white bg-opacity-0"
        >
          {ctaText}
        </a>
      ) : (
        <button className="overflow-hidden self-start px-4 py-2.5 mt-4 text-xs font-extrabold tracking-widest leading-4 text-center text-black uppercase rounded-3xl bg-white bg-opacity-0">
          {ctaText}
        </button>
      )}
    </article>
  );
};

export default ResourceCard;
