/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StudentSuccessStories from "./StudentSuccessStory";

interface Story {
  category: string;
  testimonial: string;
  author: string;
}

const stories: Story[] = [
  {
    category: "Private Client",
    testimonial:
      "She is a mentor you want to keep by your side for the rest of your life because she will NOT keep you stuck.",
    author: "HAANI K.",
  },
];

const StudentSuccessStoriesWrapper: React.FC = () => {
  return <StudentSuccessStories stories={stories} />;
};

export default StudentSuccessStoriesWrapper;
