/**
 * This code was generated by Builder.io.
 */
'use client'
import React from "react";
import { motion } from "framer-motion";
import PrimaryButton from '@/components/common/PrimaryButton';

interface SuccessStoryProps {
  category: string;
  testimonial: string;
  author: string;
}

const SuccessStory: React.FC<SuccessStoryProps> = ({
  category,
  testimonial,
  author,
}) => {
  return (
    <div className="flex flex-col px-5 md:px-12 pb-20 md:pb-8 pt-8 md:pt-10 lg:pt-16">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ 
          duration: 0.5,
          ease: "easeOut"
        }}
        viewport={{ once: true }}
        className="inline-flex px-4 py-2 text-xs tracking-[2.24px] uppercase bg-white rounded-full h-[32px] items-center justify-center w-fit whitespace-nowrap"
      >
        {category}
      </motion.div>

      <motion.blockquote
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ 
          duration: 0.6,
          delay: 0.2,
          ease: [0.22, 1, 0.36, 1]
        }}
        viewport={{ once: true }}
        className="mt-6 text-[20px] md:text-[16px] leading-[1.6] tracking-normal text-white"
      >
        {testimonial}
      </motion.blockquote>

      <motion.span
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ 
          duration: 0.5,
          delay: 0.3
        }}
        viewport={{ once: true }}
        className="mt-4 text-xs font-subheader tracking-widest uppercase text-white"
      >
        {author}
      </motion.span>

      <PrimaryButton href="/awakened-feminine" text="Get Inspired" />
    </div>
  );
};

export default SuccessStory;
