/**
 * This code was generated by Builder.io.
 */
"use client";

import React, { useState } from "react";
import SuccessStory from "./SuccessStory";
import NavigationArrow from "./NavigationArrow";

interface Story {
  category: string;
  testimonial: string;
  author: string;
}

interface StudentSuccessStoriesProps {
  stories: Story[];
}

const StudentSuccessStories: React.FC<StudentSuccessStoriesProps> = ({
  stories,
}) => {
  const [currentStoryIndex, setCurrentStoryIndex] = useState(0);

  const handlePrevStory = () => {
    setCurrentStoryIndex((prevIndex) =>
      prevIndex === 0 ? stories.length - 1 : prevIndex - 1
    );
  };

  const handleNextStory = () => {
    setCurrentStoryIndex((prevIndex) =>
      prevIndex === stories.length - 1 ? 0 : prevIndex + 1
    );
  };

  return (
    <section className="flex overflow-hidden flex-col items-center pt-10 md:py-16 bg-white max-md:px-5 max-sm:px-0">
      <header className="flex flex-col pt-6 pb-5 md:pb-10 max-w-full text-center text-neutral-800 ">
        <h2 className="pb-px w-full text-xs font-extrabold leading-5 uppercase tracking-[2.16px] max-md:px-5 max-md:max-w-full">
          Our clients win
        </h2>
        <h3 className="mt-3 w-[358px] md:w-full text-4xl lg:text-5xl md:tracking-wider md:leading-[62.4px] max-md:max-w-full font-ivy-presto">
          Will You Be The Next Success Story?
        </h3>
      </header>
      <main className="flex flex-col pt-8 pb-9 max-w-full">
        {/* <div className="grid grid-cols-1 sm:grid-cols-2 relative justify-center items-start w-full bg-stone-100 max-md:max-w-full"> */}
        <div className="flex flex-col sm:flex-row justify-center items-start w-full bg-stone-100 max-md:max-w-full">
          <img
            
            // src="/carousel.png"
            src="/gridImages/image39.png"
            alt="Student success story background"
            className="object-cover h-full w-full md:w-[450px] lg:w-[650px]"
          />
          <SuccessStory
            category={stories[currentStoryIndex].category}
            testimonial={stories[currentStoryIndex].testimonial}
            author={stories[currentStoryIndex].author}
          />
          {/* <NavigationArrow direction="left" onClick={handlePrevStory} />
          <NavigationArrow direction="right" onClick={handleNextStory} /> */}
        </div>
      </main>
    </section>
  );
};

export default StudentSuccessStories;
