/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button } from "@/components/ui/button";

interface SuccessStoryProps {
  category: string;
  testimonial: string;
  author: string;
}

const SuccessStory: React.FC<SuccessStoryProps> = ({
  category,
  testimonial,
  author,
}) => {
  return (
    <div className="flex inset-y-0 right-0 z-0 flex-col self-start px-12 pt-16 pb-48 bg-stone-100 max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <div className="inline-flex px-2 py-3 text-xs font-medium tracking-[2.24px] uppercase bg-white rounded-md h-[40px] items-center justify-center w-[150px] whitespace-nowrap">
        {category}
      </div>
      <blockquote className="pb-px mt-5 text-lg font-[700] tracking-normal leading-9 text-black max-md:max-w-full">
        {testimonial}
      </blockquote>
      <span className="pb-px mt-2 text-xs font-extrabold tracking-widest leading-4 uppercase text-neutral-500 max-md:max-w-full">
        {author}
      </span>
      <button
        className="px-24 pt-2.5 pb-3 mt-5 text-base tracking-wide leading-6 text-center text-white capitalize rounded-[100px] bg-[#1C1C1C] w-full md:w-[300px] max-md:px-5 shadow-none hover:shadow-none hover:bg-black/90 font-[700]"
      >
        <a
          href="https://www.marieforleo.com/success-stories"
          target="_blank"
          rel="noopener noreferrer"
        >
          Get Inspired
        </a>
      </button>
    </div>
  );
};

export default SuccessStory;
