/**
 * This code was generated by Builder.io
 */
import React from "react";

const Heading: React.FC = () => {
  return (
    <h2 className="mt-6 text-2xl font-light tracking-wide leading-8 text-orange-50 max-md:max-w-full">
      Release Your Divine Feminine Power. <br />
      Embrace <strong>Authentic Abundance</strong>, <strong>Inner Peace</strong>, and{" "}
      <strong>Spiritual Freedom</strong>
    </h2>
  );
};

export default Heading;
