/**
 * This code was generated by Builder.io
 */
import React from "react";

interface QuizCardProps {
  title: string;
  subtitle: string;
  description: string;
  imageSrc: string;
  buttonText: string;
}

const QuizCard: React.FC<QuizCardProps> = ({
  title,
  subtitle,
  description,
  imageSrc,
  buttonText,
}) => {
  return (
    <section className="flex overflow-hidden flex-wrap gap-8 py-12 pr-5 pl-12 w-full bg-rose-50 shadow-sm max-md:pl-5 max-md:max-w-full">
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className="object-contain grow shrink aspect-[0.7] max-w-[915px] w-[182px]"
      />
      <div className="flex flex-col grow shrink px-10 pb-4 min-w-[240px] w-[540px] max-md:px-5 max-md:max-w-full">
        <h2 className="z-10 pb-px text-xs font-extrabold leading-5 uppercase tracking-[2.16px] max-md:max-w-full">
          Free Quiz
        </h2>
        <h3 className="mt-3 text-3xl tracking-wider leading-[48.6px] max-md:max-w-full">
          {title}
        </h3>
        <p className="mt-2.5 tracking-normal leading-8 text-black max-md:max-w-full">
          {description}
        </p>
        <button className="px-24 pt-2.5 pb-3 mt-6 max-w-full font-bold tracking-wide leading-6 text-center text-white capitalize rounded-3xl bg-neutral-800 w-[300px] max-md:px-5">
          {buttonText}
        </button>
      </div>
    </section>
  );
};

export default QuizCard;
