/**
 * This code was generated by Builder.io
 */
import * as React from "react";
import { TextBlock } from "./TextBlock";
import { CTAButton } from "./CTAButton";

export const DreamClubHero: React.FC = () => {
  return (
    <main className="w-full bg-gradient-to-b from-neutral-950 via-black to-neutral-900 text-white text-center px-4 md:px-16">
      <section className="max-w-[900px] mx-auto py-20">
        <article className="text-xl font-light leading-8 mb-16">
          <p className="max-w-[800px] mx-auto">
            You <span className="italic">can</span> have the business — and life — you dream of. 
            You can have the wealth, joy, and{" "}
            <span className="uppercase tracking-wider">FREEDOM</span> you crave.
          </p>

          <p className="mt-8 max-w-[600px] mx-auto">
            Most importantly, you can have a <span className="italic">damn good time</span> along the way.
          </p>
        </article>

        <h1 className="text-4xl text-[#E5B5A7] uppercase tracking-[4px] leading-[54px] mb-8">
          AND IT'S ALL INSIDE OF DREAM <br /> CLUB...
        </h1>

        <p className="text-sm tracking-[2px] uppercase mb-8">
          THIS IS AN INVITE-ONLY EXPERIENCE — AVAILABILITY IS LIMITED.
        </p>

        <div className="max-w-[388px] mx-auto mb-8">
          <CTAButton 
            text="GET ON THE VIP WAITLIST NOW" 
            className="w-full bg-[#E5B5A7] text-black rounded-full px-8 py-4 font-medium tracking-wider uppercase" 
          />
        </div>

        <footer className="text-sm font-light">
          <p className="flex gap-2 justify-center items-center">
            <span>Don't see the sign-up button?</span>
            <button className="text-[#E5B5A7]">Click here</button>
            <span>to join.</span>
          </p>
        </footer>
      </section>
    </main>
  );
};
