/**
 * This code was generated by Builder.io
 */
import React from "react";
import Image from "next/image";

interface ImageComponentProps {
  src: string;
  alt: string;
}

const ImageComponent: React.FC<ImageComponentProps> = ({ src, alt }) => {
  return (
    <Image
      src={src}
      alt={alt}
      className="object-cover object-top w-full max-h-[600px]"
      height={600}
      width={200}
    />
  );
};

export default ImageComponent;
