/**
 * This code was generated by Builder.io
 */
import React from "react";
import Image from "next/image";

interface ImageComponentProps {
  src: string;
  alt: string;
}

const ImageComponent: React.FC<ImageComponentProps> = ({ src, alt }) => {
  return (
    <Image
      src={src}
      alt={alt}
      className="object-contain w-full aspect-[1.71]"
      width={500}
      height={293}
    />
  );
};

export default ImageComponent;
