/**
 * This code was generated by Builder.io
 */
export interface TextBlockProps {
  children: React.ReactNode;
  className?: string;
}

export interface CTAButtonProps {
  text: string;
  onClick?: () => void;
}
