/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Link from 'next/link';
import { motion } from "framer-motion";

interface FooterLink {
  text: string;
  href?: string;
}

const footerLinks: FooterLink[] = [
  { text: "Terms Of Use", href: "/terms-of-use" },
  { text: "Privacy Policy", href: "/privacy-policy" },
];

const BottomBar: React.FC = () => {
  return (
    <div className="flex flex-col justify-center pt-4 mt-10 w-full text-[12px] md:text-[9px] lg:text-[10px] xl:text-[12px] tracking-widest text-white uppercase border-t border-t-stone-300">
      <div className="flex md:justify-between md:items-center w-full">
        {/* Mobile Layout Container */}
        <div className="flex flex-col items-center gap-4 w-full md:hidden">
          <nav>
            <ul className="flex gap-6">
              {footerLinks.map((link, index) => (
                <motion.li 
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.2 + (index * 0.1) }}
                  className="whitespace-nowrap"
                >
                  {link.href ? (
                    <a href={link.href} className="hover:opacity-80">
                      {link.text}
                    </a>
                  ) : (
                    <span>{link.text}</span>
                  )}
                </motion.li>
              ))}
            </ul>
          </nav>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.4 }}
          >
            © 2024 GLOWING FEMME ALL RIGHTS RESERVED.
          </motion.p>
          
          <div className="flex items-center gap-1 text-[17px] md:text-[9px]">
            <motion.span
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.5 }}
            >
              DESIGNED BY
            </motion.span>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.6 }}
            >
              <Link 
                href="https://aalpha.ai" 
                target="_blank" 
                rel="noopener noreferrer"
                className="hover:opacity-80"
              >
                AALPHA.AI
              </Link>
            </motion.div>
          </div>
        </div>

        {/* Desktop Layout */}
        <div className="hidden md:flex md:justify-between md:items-center w-full">
          <nav>
            <ul className="flex gap-6">
              {footerLinks.map((link, index) => (
                <motion.li 
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.2 + (index * 0.1) }}
                  className="whitespace-nowrap"
                >
                  {link.href ? (
                    <a href={link.href} className="hover:opacity-80">
                      {link.text}
                    </a>
                  ) : (
                    <span>{link.text}</span>
                  )}
                </motion.li>
              ))}
            </ul>
          </nav>

          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.4 }}
            className="flex-1 text-center"
          >
            © 2024 GLOWING FEMME ALL RIGHTS RESERVED.
          </motion.p>

          <div className="flex items-center gap-1">
            <motion.span
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.5 }}
            >
              DESIGNED BY
            </motion.span>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.6 }}
            >
              <Link 
                href="https://aalpha.ai" 
                target="_blank" 
                rel="noopener noreferrer"
                className="hover:opacity-80"
              >
                AALPHA.AI
              </Link>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BottomBar;
