/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FooterLink {
  text: string;
  href?: string;
}

const footerLinks: FooterLink[] = [
  { text: "Terms" },
  { text: "Privacy", href: "https://www.marieforleo.com/privacy" },
];

const BottomBar: React.FC = () => {
  return (
    <div className="flex flex-col justify-center pt-4 mt-10 w-full text-xs font-bold tracking-widest leading-3 text-right text-[#F8E8D8] uppercase border-t border-t-stone-300">
      <div className="flex justify-between items-center w-full">
        <nav className="flex gap-3">
          <ul className="flex gap-3">
            {footerLinks.map((link, index) => (
              <li key={index} className="py-px whitespace-nowrap">
                {link.href ? (
                  <a href={link.href} target="_blank" rel="noopener noreferrer">
                    {link.text}
                  </a>
                ) : (
                  <span>{link.text}</span>
                )}
              </li>
            ))}
          </ul>
        </nav>
        <p className="w-full text-right">© 2024 Glowing Femme</p>
      </div>
    </div>
  );
};

export default BottomBar;
