/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image"

interface LinkItem {
  text: string;
  href: string;
}

const companyLinks: LinkItem[] = [
  { text: "About", href: "#" },
  { text: "MarieTV", href: "https://www.marieforleo.com/marietv" },
  {
    text: "The Marie Forleo Podcast",
    href: "https://www.marieforleo.com/podcast",
  },
  {
    text: "Success Stories",
    href: "https://www.marieforleo.com/success-stories",
  },
  { text: "New Here?", href: "https://www.marieforleo.com/new-here" },
  { text: "Free Tools", href: "https://www.marieforleo.com/free-tools" },
  { text: "Press & Media", href: "https://www.marieforleo.com/press-media" },
  { text: "Giving Back", href: "https://www.marieforleo.com/giving-back" },
  { text: "How We Roll", href: "https://www.marieforleo.com/how-we-roll" },
  { text: "Jobs", href: "https://www.marieforleo.com/jobs" },
];

const CompanyLinks: React.FC = () => {
  return (
    <section className="flex flex-col grow shrink   pt-6 pb-16 ">
      <h2 className="text-xs font-extrabold leading-5 text-white uppercase whitespace-nowrap tracking-[2.16px]">
        Company
      </h2>
      <nav className="mt-3">
        <ul className="flex flex-col items-start w-full text-sm tracking-wide leading-7 text-white">
          {companyLinks.map((link, index) => (
            <li key={index} className="flex items-start pb-px">
              <a href={link.href} target="_blank" rel="noopener noreferrer">
                {link.text}
              </a>
            </li>
          ))}
        </ul>
      </nav>
      <div className="flex flex-col items-start pt-2 pb-2.5 mt-10 w-full">
        <div className="flex items-center max-w-full ">
          <div className="flex overflow-hidden items-start self-stretch my-auto">
            <div className="flex overflow-hidden flex-col justify-center items-center min-h-[31px] w-[27px]">
              <Image
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/77f3edd69595841b37b1fda1a4f4d346a1ffb9af5a11c28d98d96fe804bce9c8?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a"
                alt="Help icon"
                className="object-contain w-full aspect-[0.87]"
                width={500}
                height={500}
              />
            </div>
          </div>
          <span className="self-stretch pl-3 my-auto text-sm italic tracking-wider leading-7 text-white">
            Need Help?
          </span>
        </div>
      </div>
      <a
        href="#"
        className="overflow-hidden self-start px-24 pt-2.5 pb-3 mt-7 text-base font-bold tracking-wide leading-6 text-center text-white capitalize rounded-3xl bg-white bg-opacity-0 max-md:px-5"
      >
        program login
      </a>
    </section>
  );
};

export default CompanyLinks;
