/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsletterSignup from "./NewsletterSignup";
import CompanyLinks from "./CompanyLinks";
import CoursesAndBooks from "./CoursesAndBooks";
import BottomBar from "./BottomBar";
import Image from 'next/image';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col items-center bg-ramsha-primary">
      <div className="flex flex-col xl:mx-[120px] xl:px-[40px] xl:pt-[96px] xl:pb-[12px] lg:px-[54px] lg:pt-[82px] lg:pb-[86px] md:px-[40px] md:pt-[80px] md:pb-[72px] px-[21px] pt-[64px] pb-[56px] w-full">
        <div className="flex items-center self-start">
          {/* <Image
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e3dbabc984bf7a46dd6d417877c04afea8b7820a34d9c4c8949f8026548bbd8f?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a"
            alt="Company logo"
            className="object-contain self-stretch my-auto w-[307px]"
            width={1100}
            height={111}
            sizes="(max-width: 768px) 240px, 307px"
            quality={90}
          /> */}
          <h1 className="uppercase text-4xl font-seasons text-ramsha-tertiary">
            Glowing Femme
          </h1>
        </div>
        <div className=" grid grid-cols-1 md:grid-cols-12 md:gap-5 lg:gap-10 items-start">
          <div className="md:col-span-5">
            <NewsletterSignup />
          </div>
          <div className="md:col-span-4">
            <CompanyLinks />
          </div>
          <div className="md:col-span-3">
            <CoursesAndBooks />
          </div>
        </div>
        <BottomBar />
      </div>
    </footer>
  );
};

export default Footer;
