/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NewsletterSignup from "./NewsletterSignup";
import CompanyLinks from "./CompanyLinks";
import CoursesAndBooks from "./CoursesAndBooks";
import BottomBar from "./BottomBar";
import Image from 'next/image';
import Link from 'next/link';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col items-center bg-ramsha-primary">
      <div className="flex flex-col xl:mx-[120px] xl:px-[40px] xl:pt-[96px] xl:pb-[12px] lg:px-[54px] lg:pt-[82px] lg:pb-[86px] md:px-[40px] md:pt-[80px] md:pb-[72px] px-[21px] pt-[64px] pb-[56px] w-full">
        <div className="flex items-center self-start">
          <Link href="/">
            <h1 className="uppercase text-4xl font-seasons text-ramsha-tertiary hover:opacity-80 transition-opacity cursor-pointer">
              Glowing Femme
            </h1>
          </Link>
        </div>
        <div className=" grid grid-cols-1 md:grid-cols-12 md:gap-5 lg:gap-10 items-start">
          <div className="md:col-span-5">
            <NewsletterSignup />
          </div>
          <div className="md:col-span-4">
            <CompanyLinks />
          </div>
          <div className="md:col-span-3">
            <CoursesAndBooks />
          </div>
        </div>
        <BottomBar />
      </div>
    </footer>
  );
};

export default Footer;
