/**
 * This code was generated by Builder.io.
 */
'use client'
import React from "react";
import { motion } from "framer-motion";
import NewsletterSignup from "./NewsletterSignup";
import CompanyLinks from "./CompanyLinks";
import CoursesAndBooks from "./CoursesAndBooks";
import BottomBar from "@/components/common/BottomBar";
import Link from 'next/link';

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col items-center bg-ramsha-primary">
      <div className="flex flex-col xl:mx-[120px] xl:px-[40px] xl:pt-[96px] lg:px-[54px] lg:pt-[82px] md:px-[40px] md:pt-[80px] px-[21px] pt-[64px] w-full">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ 
            duration: 0.5,
            ease: "easeOut"
          }}
          viewport={{ once: true }}
          className="flex items-center self-start"
        >
          <Link href="/">
            <h1 className="uppercase text-4xl font-logo text-ramsha-tertiary hover:opacity-80 transition-opacity cursor-pointer">
              Glowing Femme
            </h1>
          </Link>
        </motion.div>

        <div className="flex flex-col gap-8 md:grid md:grid-cols-12 md:gap-5 lg:gap-10 items-start">
          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ 
              duration: 0.6,
              delay: 0.2,
              ease: [0.22, 1, 0.36, 1]
            }}
            viewport={{ once: true }}
            className="w-full md:col-span-5"
          >
            <NewsletterSignup />
          </motion.div>

          <div className="grid grid-cols-2 gap-4 w-full md:contents">
            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ 
                duration: 0.6,
                delay: 0.3,
                ease: [0.22, 1, 0.36, 1]
              }}
              viewport={{ once: true }}
              className="md:col-span-4"
            >
              <CompanyLinks />
            </motion.div>

            <motion.div 
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ 
                duration: 0.6,
                delay: 0.4,
                ease: [0.22, 1, 0.36, 1]
              }}
              viewport={{ once: true }}
              className="md:col-span-3"
            >
              <CoursesAndBooks />
            </motion.div>
          </div>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ 
            duration: 0.5,
            delay: 0.5,
            ease: "easeOut"
          }}
          viewport={{ once: true }}
        >
          <BottomBar />
        </motion.div>
      </div>
    </footer>
  );
};

export default Footer;
