/**
 * This code was generated by Builder.io
 */
import React from "react";
import { CoachSection } from "./CoachSection";

const RamshaSuhailSection: React.FC = () => {
  const headingText = [
    "What If Your Divine",
    "Purpose Could Unlock",
    "The Barakah and",
    "ABUNDANCE You Seek?",
  ];

  const paragraphs = [
    "Bismillah sister, your soul is whispering: Allah has written a beautiful path for you.",
    "You can embody the divine feminine energy that Allah blessed you with — complete with the spiritual abundance, impact, and soul-deep fulfillment written in your Qadr.",
    "Through sacred healing, tawakkul (divine surrender), and alignment with your fitrah, you'll find the inner peace your heart craves.",
    "SubhanAllah, if you're reading these words, Allah has guided you here for a reason.",
  ];

  const strongText = {
    regular: "Your soul carries a wisdom that connects you to",
    italic: "Allah's infinite mercy... and deep down, you feel it.",
  };

  const authorInfo = [
    "I'm Ramsha Suhail — founder of Awakened Feminine, spiritual guide, and transformational mentor for Muslim women seeking to align with their divine purpose.",
    "Alhamdulillah, I've helped countless sisters unlock their divine feminine power and create lives of authentic abundance through faith and surrender. Now, it's your turn to rise.",
  ];

  const imageSrc = "/ramsha-pics/webp/gf5924.webp";

  return (
    <CoachSection
      headingText={headingText}
      paragraphs={paragraphs}
      strongText={strongText}
      authorInfo={authorInfo}
      imageSrc={imageSrc}
    />
  );
};

export default RamshaSuhailSection;
