/**
 * This code was generated by Builder.io
 */
import React from "react";

interface StrongTextProps {
  regular: string;
  italic: string;
}

export const StrongText: React.FC<StrongTextProps> = ({ regular, italic }) => (
  <div className="flex flex-col pb-1 mt-4 w-full max-md:max-w-full">
    <p className="text-base">
      SubhanAllah,
      <span className="font-bold">
        {" "}
        {regular}
        <span className="text-black"> {italic} </span>
        <span className="italic text-black">bi'ithnillah</span>
        <span className="text-black">.</span>
      </span>
    </p>
  </div>
);
