/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MediaLogo from "./MediaLogo";
import BlurFade from "@/components/magicui/blur-fade";

type MediaLogoData = {
  src: string;
  alt: string;
  className: string;
};

const mediaLogos: MediaLogoData[] = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/77ee9cf649be428d9c26ec3f194bb6721e9970626d1ca77396cf5d63b971c3e3?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 1",
    className: "aspect-[3.88] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/60ccfe6f2ce4239b941a93d81a93726bee32b5b6971e804baff777a798c7b6b6?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 2",
    className: "aspect-[1.33] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/07db8f4f7ff03b4d139ece7abc6fd24c3bbd7213e7b779d80f0dd259cbaf9234?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 3",
    className: "aspect-[2.54] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/a119ce368cd66dca2383df46a57be9543694b1c3033ba484fb40c7cdba27009c?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 4",
    className: "aspect-[1.33] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6134904590e23c63342bb7239877630236174f2348ca01de2e0f2c2a2018fd0e?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 5",
    className: "aspect-[1.96] w-[88px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9f69cdbfd4ad7061860cf91a514052bdb3a6d8feb2c03e06a6824626e1f52857?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 6",
    className: "aspect-[4.24] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/4609e069174a75b4739ddf8f0c33597b3aea4b65b75f5737a4df6cfcf48c98a5?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 7",
    className: "aspect-[3.56] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/49fc9871384a4bd3f1090ffe1399f266b7e7c8a71dc67268d7da4cbe5452550b?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 8",
    className: "aspect-[4.69] w-[89px]",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/823afd5ba5bcd78013ef63c5aaab9ddb45307b7c3b449984d29d1fe192d3f76e?placeholderIfAbsent=true&apiKey=3445d620e72b4cd99c6f91e1d18e316a",
    alt: "Media Logo 9",
    className: "aspect-[5.24] w-[89px]",
  },
];

const MediaLogos: React.FC = () => {
  return (
    <section className="flex flex-col items-center gap-6 px-20 pt-10 md:pb-14 lg:pt-20 lg:pb-32 bg-neutral-800 w-full max-md:px-5 max-md:pb-24">
      <BlurFade>
        <h2 className="pb-px w-full text-xs font-extrabold leading-5 text-center text-white uppercase  tracking-[2.16px] max-md:max-w-full">
          You Might Have Seen Me On
        </h2>
      </BlurFade>
      <BlurFade>
        <div className="grid grid-cols-3 md:grid-cols-9 gap-10 items-center self-center mt-7 w-full max-w-[1200px]">
          {mediaLogos.map((logo, index) => (
            <MediaLogo key={index} {...logo} />
          ))}
        </div>
      </BlurFade>
    </section>
  );
};

export default MediaLogos;
