/**
 * This code was generated by Builder.io
 */
import React from "react";

interface ContainerProps {
  children: React.ReactNode;
}

export const Container: React.FC<ContainerProps> = ({ children }) => {
  return (
    <div className="flex flex-col px-14 pt-20 pb-28 w-full max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <div className="flex flex-col w-full max-md:max-w-full">{children}</div>
    </div>
  );
};
