/**
 * This code was generated by Builder.io
 */
import React from "react";
import { Container } from "./Container";
import { Heading } from "./Heading";
import { Description } from "./Description";

interface FreeToolsSectionProps {
  title: string;
  description: string[];
}

export const FreeToolsSection: React.FC<FreeToolsSectionProps> = ({
  title,
  description,
}) => {
  return (
    <section className="flex overflow-hidden flex-col items-center text-center bg-stone-100">
      <Container>
        <Heading>{title}</Heading>
        <Description lines={description} />
      </Container>
    </section>
  );
};
